import type { Klacht } from "./types";

export const klachten2: Klacht[] = [
  {
    slug: "neuralgische-amyotrofie-behandeling",
    name: "Neuralgische amyotrofie (NA)",
    shortName: "Neuralgische amyotrofie",
    category: "klacht",
    seoTitle: "Neuralgische amyotrofie behandelen | Kaakfysiotherapie",
    metaDescription:
      "Last van plotselinge schouder- of nekpijn en krachtsverlies? Lees alles over neuralgische amyotrofie en hoe fysiotherapie kan helpen.",
    lead: "Plotselinge heftige pijn in schouder of nek, gevolgd door krachtsverlies?",
    card: "Plotselinge zenuwpijn met krachtsverlies in schouder, nek of arm — gespecialiseerde begeleiding, aangesloten bij het NA-netwerk van het Radboudumc.",
    sections: [
      {
        id: "introductie",
        title: "Plotselinge pijn en krachtsverlies?",
        blocks: [
          { type: "p", text: "Heeft u plotseling heftige pijn in uw schouder, nek of arm gekregen, gevolgd door krachtsverlies of een \u201clam gevoel\u201d? Dan kan er sprake zijn van neuralgische amyotrofie. Deze aandoening kan behoorlijk schrikken zijn, zeker omdat de klachten vaak onverwacht ontstaan." },
          { type: "p", text: "Veel mensen zoeken hulp omdat ze hun arm minder goed kunnen gebruiken, pijn ervaren of merken dat dagelijkse handelingen moeilijker gaan. Een gespecialiseerde fysiotherapeut kan u helpen om grip te krijgen op uw klachten en het herstel te ondersteunen." },
        ],
      },
      {
        id: "wat-is-na",
        title: "Wat is neuralgische amyotrofie?",
        blocks: [
          { type: "p", text: "Neuralgische amyotrofie is een aandoening van de zenuwen, meestal in de schouderregio (plexus brachialis). De naam klinkt ingewikkeld, maar betekent eigenlijk:" },
          { type: "list", items: ["neuralgisch = zenuwpijn", "amyotrofie = spierverlies of spierzwakte"] },
          { type: "p", text: "Bij deze aandoening raken zenuwen tijdelijk ontstoken of ge\u00efrriteerd. Hierdoor ontstaat eerst vaak hevige pijn, gevolgd door spierzwakte of zelfs uitval van spieren." },
          { type: "p", text: "Hoewel de klachten meestal in de schouder en arm voorkomen, kunnen ze ook invloed hebben op de nek en soms zelfs het hoofd-halsgebied. Daarom kan een orofaciaal fysiotherapeut, gespecialiseerd in het hoofd-halsgebied, een belangrijke rol spelen in het herstel." },
        ],
      },
      {
        id: "symptomen",
        title: "Symptomen van neuralgische amyotrofie",
        blocks: [
          { type: "p", text: "De klachten bij neuralgische amyotrofie verlopen vaak in fases. Herkenbare symptomen zijn:" },
          { type: "h3", text: "Hevige pijn (acute fase)" },
          { type: "list", items: [
            "plotselinge, scherpe of brandende pijn in schouder of nek",
            "pijn die kan uitstralen naar arm of schouderblad",
            "vaak erger in de nacht",
          ] },
          { type: "h3", text: "Krachtsverlies (na enkele dagen tot weken)" },
          { type: "list", items: [
            "moeite met het tillen van de arm",
            "verminderde kracht in schouder of arm",
            "spieren die dunner worden (spieratrofie)",
          ] },
          { type: "h3", text: "Bewegingsproblemen" },
          { type: "list", items: [
            "beperkte bewegingsvrijheid",
            "veranderde manier van bewegen (compensaties)",
            "moeite met dagelijkse handelingen zoals aankleden",
          ] },
          { type: "h3", text: "Andere mogelijke klachten" },
          { type: "list", items: [
            "tintelingen of doof gevoel",
            "vermoeidheid van spieren",
            "nekklachten of hoofdpijn door compensatie",
          ] },
          { type: "p", text: "De combinatie van pijn en krachtsverlies maakt deze aandoening vaak ingrijpend in het dagelijks leven." },
        ],
      },
      {
        id: "oorzaken",
        title: "Mogelijke oorzaken",
        blocks: [
          { type: "p", text: "De exacte oorzaak van neuralgische amyotrofie is niet altijd duidelijk. Wel zijn er factoren die een rol kunnen spelen:" },
          { type: "list", items: [
            "overbelasting of fysieke stress",
            "virale infecties (bijvoorbeeld griep)",
            "operaties of vaccinaties",
            "auto-immuunreacties (het lichaam valt eigen zenuwen aan)",
            "erfelijke aanleg (in zeldzame gevallen)",
          ] },
          { type: "p", text: "Vaak ontstaat de aandoening plotseling, zonder duidelijke aanleiding. Dit maakt het voor pati\u00ebnten soms lastig te begrijpen wat er precies gebeurt." },
        ],
      },
      {
        id: "wanneer-hulp",
        title: "Wanneer is het verstandig om hulp te zoeken?",
        blocks: [
          { type: "p", text: "Het is belangrijk om tijdig hulp te zoeken, zeker bij de volgende signalen:" },
          { type: "list", items: [
            "hevige schouder- of nekpijn zonder duidelijke oorzaak",
            "snel optredend krachtsverlies in arm of schouder",
            "problemen met dagelijkse bewegingen",
            "aanhoudende klachten die niet verbeteren",
            "twijfel over de oorzaak van uw klachten",
          ] },
          { type: "p", text: "Een vroege beoordeling helpt om de juiste diagnose te stellen en complicaties te voorkomen. Daarnaast geeft het u duidelijkheid en rust." },
        ],
      },
      {
        id: "hoe-helpt",
        title: "Hoe kan een fysiotherapeut helpen?",
        blocks: [
          { type: "p", text: "Als fysiotherapeut ben ik gespecialiseerd in neuralgische amyotrofie, met uitgebreide kennis van zenuwen, spieren en gewrichten in deze regio. Ik ben aangesloten bij het netwerk van NA-therapeuten vanuit het Radboudumc." },
          { type: "h3", text: "Onderzoek" },
          { type: "p", text: "Tijdens het eerste consult wordt uitgebreid gekeken naar:" },
          { type: "list", items: [
            "uw klachten en het verloop ervan",
            "kracht en spierfunctie",
            "bewegingsmogelijkheden van nek, arm en schouder",
            "houding en bewegingspatronen",
            "eventuele compensaties in het lichaam",
          ] },
          { type: "p", text: "Indien nodig wordt samengewerkt met uw huisarts of specialist en een gespecialiseerd ergotherapeut." },
          { type: "h3", text: "Begeleiding en uitleg" },
          { type: "p", text: "Een belangrijk onderdeel van de behandeling is begrip van uw klachten. U krijgt uitleg over het verloop van neuralgische amyotrofie, wat u wel en niet moet doen en hoe u overbelasting voorkomt. Dit helpt om onzekerheid te verminderen en vertrouwen in herstel te vergroten." },
        ],
      },
      {
        id: "behandeling",
        title: "Behandeling in de praktijk",
        blocks: [
          { type: "p", text: "De behandeling van neuralgische amyotrofie is gericht op herstel van functie, het verminderen van klachten en het voorkomen van compensatieproblemen." },
          { type: "h3", text: "Oefentherapie" },
          { type: "list", items: ["training van co\u00f6rdinatie en controle", "geleidelijke opbouw van belasting"] },
          { type: "h3", text: "Houdings- en bewegingsadvies" },
          { type: "list", items: ["inzicht in gezonde bewegingspatronen", "voorkomen van overbelasting", "optimaliseren van dagelijkse activiteiten"] },
          { type: "h3", text: "Manuele technieken" },
          { type: "list", items: ["mobilisaties van nek en schouder", "verminderen van stijfheid en spanning", "ondersteunen van bewegingsvrijheid"] },
          { type: "h3", text: "Kaak- en nekbehandeling" },
          { type: "p", text: "Omdat klachten zich kunnen uitbreiden naar het hoofd-halsgebied, wordt ook gekeken naar spanning in kaakspieren, nekbelasting en de relatie met hoofdpijn." },
          { type: "h3", text: "Pijnmanagement" },
          { type: "list", items: ["adviezen voor het omgaan met pijn", "doseren van activiteiten", "eventueel ontspanningsoefeningen"] },
          { type: "p", text: "Herstel bij neuralgische amyotrofie kost tijd. Samen werken we aan een verantwoord en geleidelijk hersteltraject." },
        ],
      },
    ],
    faq: [
      { q: "Hoe lang duurt het herstel?", a: "Het herstel kan variëren van enkele maanden tot soms langer dan een jaar. De meeste mensen herstellen grotendeels, maar dit vraagt tijd en begeleiding." },
      { q: "Gaat de pijn vanzelf over?", a: "De hevige pijnfase neemt meestal vanzelf af, maar spierzwakte en functionele beperkingen blijven vaak bestaan zonder gerichte behandeling." },
      { q: "Kan fysiotherapie echt helpen?", a: "Ja, fysiotherapie helpt bij het herstellen van coördinatie, het verbeteren van bewegingspatronen en het voorkomen van verkeerde compensaties en overbelasting." },
      { q: "Mag ik blijven bewegen?", a: "Ja, maar gedoseerd. Te veel belasting kan klachten verergeren, terwijl te weinig bewegen het herstel vertraagt. Begeleiding hierin is belangrijk." },
      { q: "Komt het vaker terug?", a: "In de meeste gevallen is het een eenmalige episode. In zeldzame gevallen kan het terugkeren." },
    ],
    closing: {
      title: "Klachten die passen bij neuralgische amyotrofie?",
      paragraphs: [
        "Neuralgische amyotrofie kan een grote impact hebben op uw dagelijks functioneren. De combinatie van pijn en krachtsverlies zorgt vaak voor onzekerheid en beperkingen. Met de juiste begeleiding kunt u echter stap voor stap werken aan herstel.",
        "Heeft u klachten die passen bij neuralgische amyotrofie of twijfelt u hierover? Neem gerust contact op voor advies of een afspraak. We denken graag met u mee.",
      ],
    },
  },
  {
    slug: "globusklachten-keel-brokgevoel-behandeling",
    name: "Globusklachten (brokgevoel in de keel)",
    shortName: "Globus- & keelklachten",
    category: "klacht",
    seoTitle: "Globusklachten: brokgevoel in de keel behandelen",
    metaDescription:
      "Last van een brokgevoel in de keel? Ontdek wat globusklachten zijn en hoe orofaciale fysiotherapie kan helpen bij herstel.",
    lead: "Het gevoel dat er iets vastzit in uw keel, terwijl er niets zit?",
    card: "Een brok- of drukgevoel in de keel zonder medische oorzaak, vaak samenhangend met spierspanning en ademhaling.",
    sections: [
      {
        id: "introductie",
        title: "Een brok in de keel?",
        blocks: [
          { type: "p", text: "Heeft u het gevoel dat er iets vastzit in uw keel, terwijl er eigenlijk niets zit? Dit wordt vaak omschreven als een \u201cbrok in de keel\u201d en kan erg vervelend en soms zelfs beangstigend zijn. Veel mensen maken zich zorgen of er iets ernstigs aan de hand is." },
          { type: "p", text: "Globusklachten komen regelmatig voor en hebben vaak geen duidelijke medische oorzaak. Toch kunnen ze uw dagelijks functioneren flink be\u00efnvloeden, bijvoorbeeld bij slikken, praten of ontspannen. Een orofaciaal fysiotherapeut kan helpen om de oorzaak van uw klachten in kaart te brengen en u te begeleiden naar herstel." },
        ],
      },
      {
        id: "wat-is-globus",
        title: "Wat is globus?",
        blocks: [
          { type: "p", text: "Globus, ook wel globusgevoel of globus pharyngeus genoemd, is het gevoel dat er een brok of druk in de keel zit, zonder dat er daadwerkelijk iets aanwezig is." },
          { type: "p", text: "Het is geen ziekte op zich, maar een symptoom dat verschillende oorzaken kan hebben. Vaak is er geen afwijking zichtbaar bij medisch onderzoek, wat het soms lastig maakt om te begrijpen waar de klachten vandaan komen." },
          { type: "p", text: "Belangrijk om te weten: globusklachten zijn meestal onschuldig, maar kunnen wel langdurig en hinderlijk aanwezig zijn." },
        ],
      },
      {
        id: "symptomen",
        title: "Symptomen van globus",
        blocks: [
          { type: "p", text: "Mensen met globusklachten herkennen vaak \u00e9\u00e9n of meerdere van de volgende klachten:" },
          { type: "list", items: [
            "gevoel van een brok of iets dat vastzit in de keel",
            "druk of spanning in de hals",
            "moeite met slikken (zonder dat eten echt blijft steken)",
            "het gevoel vaker te moeten slikken",
            "schrapen van de keel",
            "veranderd stemgevoel of heesheid",
            "spanningsgevoel in de kaak of nek",
          ] },
          { type: "p", text: "Opvallend is dat de klachten vaak minder aanwezig zijn tijdens eten of drinken en juist sterker opvallen in rust of bij stress." },
        ],
      },
      {
        id: "hoe-helpt",
        title: "Hoe kan een orofaciaal fysiotherapeut helpen?",
        blocks: [
          { type: "p", text: "Een orofaciaal fysiotherapeut is gespecialiseerd in klachten in het hoofd-halsgebied, zoals kaak-, nek- en slikklachten." },
          { type: "h3", text: "Intake en onderzoek" },
          { type: "p", text: "Tijdens de eerste afspraak wordt uitgebreid gekeken naar:" },
          { type: "list", items: [
            "uw klachten en wanneer deze optreden",
            "spanning in de spieren van kaak, hals en nek",
            "houding en bewegingspatronen",
            "ademhaling",
            "eventuele invloed van stress",
          ] },
          { type: "p", text: "Het doel is om inzicht te krijgen in de factoren die uw klachten in stand houden." },
          { type: "h3", text: "Persoonlijke benadering" },
          { type: "p", text: "Geen twee pati\u00ebnten zijn hetzelfde. Daarom wordt de behandeling afgestemd op uw specifieke situatie en klachtenpatroon." },
        ],
      },
      {
        id: "behandeling",
        title: "Behandeling van globusklachten in de praktijk",
        blocks: [
          { type: "p", text: "De behandeling van globusklachten richt zich vaak op het verminderen van spanning en het herstellen van een gezond bewegings- en ademhalingspatroon." },
          { type: "h3", text: "Oefentherapie" },
          { type: "p", text: "U leert gerichte oefeningen om spanning in de keel en hals te verminderen, de kaakspieren te ontspannen en uw ademhaling te verbeteren." },
          { type: "h3", text: "Houdingsadvies" },
          { type: "p", text: "Een goede houding vermindert belasting op de nek en keelregio. U krijgt praktische tips voor werk, thuis en ontspanning." },
          { type: "h3", text: "Manuele technieken" },
          { type: "p", text: "De fysiotherapeut kan zachte technieken toepassen om spieren en weefsels in de hals- en kaakregio te ontspannen." },
          { type: "h3", text: "Ademhalingsoefeningen" },
          { type: "p", text: "Een rustige, lage ademhaling helpt om spanning in het lichaam te verminderen en het globusgevoel te verlichten." },
          { type: "h3", text: "Bewustwording en educatie" },
          { type: "p", text: "Inzicht in uw klachten is een belangrijk onderdeel van herstel. U leert herkennen wanneer spanning toeneemt en hoe u hier zelf invloed op kunt uitoefenen." },
          { type: "h3", text: "Ontspanning en stressmanagement" },
          { type: "p", text: "Omdat stress vaak een rol speelt, wordt er aandacht besteed aan ontspanning en het omgaan met spanning." },
        ],
      },
    ],
    faq: [
      { q: "Is globus gevaarlijk?", a: "Nee, globusklachten zijn meestal onschuldig. Het gevoel kan vervelend zijn, maar wijst zelden op een ernstige aandoening." },
      { q: "Gaat globus vanzelf over?", a: "Bij sommige mensen verdwijnen de klachten vanzelf. Als de klachten langer aanhouden, kan behandeling helpen om het herstel te versnellen." },
      { q: "Heeft stress echt zoveel invloed?", a: "Ja, stress kan leiden tot verhoogde spierspanning en een veranderd ademhalingspatroon, wat het brokgevoel kan versterken." },
      { q: "Helpt fysiotherapie echt bij globusklachten?", a: "Ja, vooral wanneer spierspanning, houding of ademhaling een rol spelen. Veel mensen ervaren duidelijke vermindering van klachten." },
      { q: "Moet ik eerst naar de huisarts?", a: "Bij nieuwe klachten is het verstandig om eerst uw huisarts te raadplegen om medische oorzaken uit te sluiten." },
    ],
    closing: {
      title: "Blijft u last houden van een brokgevoel in de keel?",
      paragraphs: [
        "Een brokgevoel in de keel kan onzekerheid en spanning geven, zeker als u niet goed weet waar het vandaan komt. Gelukkig zijn globusklachten vaak goed te behandelen, zeker wanneer er sprake is van spierspanning of een verstoord ademhalingspatroon.",
        "Blijft u last houden van een brokgevoel in de keel? Neem gerust contact op voor meer informatie of het maken van een afspraak. Samen kijken we naar de oorzaak van uw klachten en werken we aan een passende oplossing.",
      ],
    },
  },
  {
    slug: "hoofd-halsoncologie-fysiotherapie",
    name: "Hoofd-halsoncologie",
    shortName: "Hoofd-halsoncologie",
    category: "klacht",
    seoTitle: "Hoofd-halsoncologie | Fysiotherapie bij herstel",
    metaDescription:
      "Klachten na hoofd-halskanker? Orofaciale fysiotherapie helpt bij pijn, slikken en bewegen. Plan een afspraak voor persoonlijk advies.",
    lead: "Leven na hoofd-halskanker: ondersteuning bij herstel.",
    card: "Begeleiding bij herstel tijdens of na kanker in het hoofd-halsgebied: mondopening, slikken, littekens en belastbaarheid.",
    sections: [
      {
        id: "introductie",
        title: "Leven na hoofd-halskanker: ondersteuning bij herstel",
        blocks: [
          { type: "p", text: "Een behandeling voor hoofd-halskanker is vaak intensief en heeft veel impact op het dagelijks leven. Klachten zoals pijn, vermoeidheid, slikproblemen of beperkingen in het bewegen van de kaak en nek komen regelmatig voor \u2013 ook lange tijd na de medische behandeling." },
          { type: "p", text: "Veel mensen merken dat het herstel niet vanzelf gaat. Een orofaciaal fysiotherapeut kan helpen om klachten te verminderen en het functioneren in het dagelijks leven te verbeteren." },
        ],
      },
      {
        id: "wat-is-oncologie",
        title: "Wat is hoofd-halsoncologie?",
        blocks: [
          { type: "p", text: "Hoofd-halsoncologie richt zich op kanker in het gebied van het hoofd en de hals. Denk hierbij aan tumoren in de mond, keel, tong, speekselklieren of het strottenhoofd. De behandeling bestaat vaak uit een combinatie van:" },
          { type: "list", items: ["operatie", "bestraling (radiotherapie)", "chemotherapie"] },
          { type: "p", text: "Hoewel deze behandelingen noodzakelijk zijn, kunnen ze ook bijwerkingen geven. Littekenvorming, spierspanning en veranderingen in zenuwen of weefsels kunnen klachten veroorzaken die invloed hebben op spreken, eten, slikken en bewegen." },
        ],
      },
      {
        id: "symptomen",
        title: "Symptomen van klachten na hoofd-halsoncologie",
        blocks: [
          { type: "p", text: "Na behandeling van hoofd-halskanker kunnen verschillende klachten ontstaan. Niet iedereen ervaart dezelfde symptomen, maar veelvoorkomende klachten zijn:" },
          { type: "h3", text: "Pijn en stijfheid" },
          { type: "list", items: ["pijn in de kaak, hals of schouders", "stijf gevoel in de nek", "beperkte beweeglijkheid"] },
          { type: "h3", text: "Problemen met kauwen en slikken" },
          { type: "list", items: ["moeite met het openen van de mond (trismus)", "pijn bij kauwen", "slikklachten of het gevoel dat eten blijft hangen"] },
          { type: "h3", text: "Verminderde functie van mond en kaak" },
          { type: "list", items: ["verminderde kracht of co\u00f6rdinatie", "moeite met spreken", "verandering in kaakstand of beweging"] },
          { type: "h3", text: "Vermoeidheid en algehele belasting" },
          { type: "list", items: ["sneller moe zijn", "minder belastbaar in het dagelijks leven"] },
          { type: "h3", text: "Lymfoedeem (vochtophoping)" },
          { type: "list", items: ["zwelling in het gezicht of de hals", "drukkend of zwaar gevoel"] },
          { type: "p", text: "Deze klachten kunnen het dagelijks functioneren flink be\u00efnvloeden, zoals eten, praten, werken en sociale activiteiten." },
        ],
      },
      {
        id: "oorzaken",
        title: "Mogelijke oorzaken van deze klachten",
        blocks: [
          { type: "p", text: "De klachten na hoofd-halsoncologische behandelingen ontstaan vaak door een combinatie van factoren:" },
          { type: "list", items: [
            "operaties kunnen spieren, zenuwen en bindweefsel beschadigen",
            "bestraling kan zorgen voor verharding van weefsels (fibrose)",
            "littekenvorming beperkt de beweeglijkheid",
            "spanning in spieren door compensatiegedrag",
            "verminderde conditie door ziekte en behandeling",
          ] },
          { type: "p", text: "Ook angst, spanning of veranderingen in lichaamservaring kunnen een rol spelen bij het in stand houden van klachten." },
        ],
      },
      {
        id: "wanneer-hulp",
        title: "Wanneer is het verstandig om hulp te zoeken?",
        blocks: [
          { type: "p", text: "Het is verstandig om een orofaciaal fysiotherapeut te raadplegen als u:" },
          { type: "list", items: [
            "moeite heeft met het openen van de mond",
            "pijn ervaart in de kaak, nek of het gezicht",
            "problemen heeft met kauwen of slikken",
            "beperkingen voelt in uw dagelijks functioneren",
            "zwelling heeft in het hoofd-halsgebied",
            "merkt dat herstel uitblijft of stagneert",
          ] },
          { type: "p", text: "Ook als u twijfelt of fysiotherapie iets voor u kan betekenen, is het zinvol om dit te laten beoordelen. Vroege begeleiding kan klachten helpen voorkomen of verminderen." },
        ],
      },
      {
        id: "hoe-helpt",
        title: "Hoe kan een orofaciaal fysiotherapeut helpen?",
        blocks: [
          { type: "p", text: "Een orofaciaal fysiotherapeut is gespecialiseerd in klachten van het hoofd, gezicht en de hals. Bij klachten na hoofd-halsoncologie wordt de behandeling altijd afgestemd op uw persoonlijke situatie." },
          { type: "h3", text: "Intake en onderzoek" },
          { type: "p", text: "Tijdens de eerste afspraak wordt gekeken naar:" },
          { type: "list", items: [
            "uw klachten en hulpvraag",
            "beweeglijkheid van kaak, nek en schouders",
            "spierspanning",
            "littekens en weefselkwaliteit",
            "ademhaling en houding",
            "kauw- en slikfunctie",
          ] },
          { type: "p", text: "Op basis hiervan wordt een behandelplan opgesteld." },
        ],
      },
      {
        id: "behandeling",
        title: "Behandeling in de praktijk",
        blocks: [
          { type: "p", text: "De behandeling is gericht op het verbeteren van functie, het verminderen van klachten en het vergroten van zelfvertrouwen in bewegen." },
          { type: "h3", text: "Oefentherapie" },
          { type: "list", items: ["verbeteren van mondopening", "oefeningen voor kaak- en nekspieren", "training van slik- en kauwfunctie", "opbouw van belastbaarheid"] },
          { type: "h3", text: "Manuele technieken" },
          { type: "list", items: ["mobiliseren van kaak en nek", "behandeling van stijve spieren", "verbeteren van weefselglijbaarheid"] },
          { type: "h3", text: "Littekentherapie" },
          { type: "list", items: ["soepeler maken van littekenweefsel", "verminderen van verklevingen"] },
          { type: "h3", text: "Behandeling van lymfoedeem" },
          { type: "list", items: ["advies en oefeningen bij zwelling", "eventueel manuele lymfedrainage"] },
          { type: "h3", text: "Houding en ademhaling" },
          { type: "list", items: ["optimaliseren van houding", "verminderen van spanning in het hoofd-halsgebied"] },
          { type: "h3", text: "Voorlichting en begeleiding" },
          { type: "p", text: "U krijgt uitleg over uw klachten, advies voor thuis en begeleiding bij het opbouwen van dagelijkse activiteiten. De behandeling gebeurt altijd in overleg met u en \u2013 vaak \u2013 in samenwerking met andere zorgverleners zoals artsen, fysiotherapeuten, logopedisten en di\u00ebtisten, onder andere binnen het Oncologienetwerk Zwartewaterland." },
        ],
      },
    ],
    faq: [
      { q: "Is fysiotherapie veilig na een kankerbehandeling?", a: "Ja, fysiotherapie is veilig wanneer deze wordt afgestemd op uw medische situatie. De therapeut houdt rekening met de behandeling die u heeft gehad." },
      { q: "Kan mijn mondopening nog verbeteren?", a: "In veel gevallen wel. Met gerichte oefeningen en begeleiding kan de beweeglijkheid van de kaak vaak verbeteren." },
      { q: "Helpt fysiotherapie bij slikklachten?", a: "Ja, in samenwerking met bijvoorbeeld een logopedist kan fysiotherapie bijdragen aan het verbeteren van de slikfunctie." },
      { q: "Hoe lang duurt het herstel?", a: "Dit verschilt per persoon. Factoren zoals het type behandeling, conditie en de ernst van klachten spelen hierbij een rol." },
      { q: "Heb ik een verwijzing nodig?", a: "Bij hoofd-halsoncologie heeft u vaak recht op een chronische indicatie. Hiervoor heeft u een verwijzing nodig van uw arts of specialist. Benader uw zorgverzekeraar voor meer informatie hierover." },
    ],
    closing: {
      title: "Neem contact op voor begeleiding bij herstel",
      paragraphs: [
        "Herstellen na hoofd-halskanker vraagt tijd, aandacht en de juiste begeleiding. Blijf niet te lang rondlopen met klachten die uw dagelijks leven beïnvloeden. Een orofaciaal fysiotherapeut kan u helpen om stap voor stap weer vertrouwen te krijgen in uw lichaam en uw functioneren te verbeteren.",
        "Neem gerust contact op voor meer informatie of het maken van een afspraak. We denken graag met u mee.",
      ],
    },
  },
  {
    slug: "aanhoudende-klachten-hersenschudding-fysiotherapie",
    name: "Aanhoudende klachten na een hersenschudding",
    shortName: "Klachten na hersenschudding",
    category: "klacht",
    seoTitle: "Aanhoudende klachten na hersenschudding behandelen",
    metaDescription:
      "Blijven klachten na een hersenschudding aanhouden? Ontdek hoe orofaciale fysiotherapie helpt bij hoofdpijn, duizeligheid en kaakklachten.",
    lead: "Blijft u klachten houden na een klap op het hoofd?",
    card: "Postcommotioneel syndroom: hoofdpijn, duizeligheid of overprikkeling die na een hersenschudding blijven aanhouden.",
    sections: [
      {
        id: "introductie",
        title: "Blijft u klachten houden na een klap op het hoofd?",
        blocks: [
          { type: "p", text: "Heeft u een hersenschudding gehad en merkt u dat klachten langer aanhouden dan verwacht? Bijvoorbeeld hoofdpijn, duizeligheid, concentratieproblemen of spanning in uw kaak of nek? U bent niet de enige. Veel mensen herstellen binnen enkele weken, maar bij een deel blijven klachten bestaan. Dit wordt ook wel het postcommotioneel syndroom genoemd." },
          { type: "p", text: "Een orofaciaal fysiotherapeut kan u helpen om deze klachten beter te begrijpen \u00e9n te verminderen." },
        ],
      },
      {
        id: "wat-is-pcs",
        title: "Wat is het postcommotioneel syndroom?",
        blocks: [
          { type: "p", text: "Het postcommotioneel syndroom is een verzamelnaam voor klachten die blijven bestaan na een hersenschudding (commotio cerebri). Normaal gesproken herstellen de hersenen binnen enkele weken, maar soms blijven klachten langer aanwezig \u2014 weken tot maanden, en soms zelfs langer." },
          { type: "p", text: "Het gaat hierbij niet alleen om de hersenen zelf. Ook spieren, gewrichten en het zenuwstelsel in het hoofd-halsgebied kunnen ontregeld raken. Denk aan de nek, kaak, ogen en het evenwichtssysteem. Deze systemen werken nauw samen, waardoor klachten elkaar kunnen versterken." },
          { type: "p", text: "Het is belangrijk om te weten dat aanhoudende klachten veel voorkomen en goed behandelbaar zijn." },
        ],
      },
      {
        id: "symptomen",
        title: "Symptomen van het postcommotioneel syndroom",
        blocks: [
          { type: "p", text: "De klachten kunnen per persoon verschillen en zijn vaak een combinatie van lichamelijke, cognitieve en emotionele symptomen." },
          { type: "h3", text: "Veelvoorkomende lichamelijke klachten" },
          { type: "list", items: [
            "hoofdpijn (spanningshoofdpijn of migraine-achtig)",
            "duizeligheid of een licht gevoel in het hoofd",
            "nekpijn of stijfheid",
            "kaakklachten (pijn, knarsen, klemmen)",
            "overgevoeligheid voor licht en geluid",
            "vermoeidheid",
          ] },
          { type: "h3", text: "Cognitieve klachten" },
          { type: "list", items: ["concentratieproblemen", "vergeetachtigheid", "trager denken of moeite met multitasken"] },
          { type: "h3", text: "Emotionele en prikkelgerelateerde klachten" },
          { type: "list", items: ["prikkelbaarheid", "snel overprikkeld raken", "slaapproblemen", "angst of onzekerheid over herstel"] },
          { type: "p", text: "Vaak wisselen de klachten gedurende de dag en kunnen ze verergeren bij inspanning, stress of drukke omgevingen." },
        ],
      },
      {
        id: "oorzaken",
        title: "Mogelijke oorzaken van aanhoudende klachten",
        blocks: [
          { type: "p", text: "Aanhoudende klachten na een hersenschudding hebben meestal niet \u00e9\u00e9n duidelijke oorzaak. Het is vaak een combinatie van factoren:" },
          { type: "h3", text: "Ontregeling van het zenuwstelsel" },
          { type: "p", text: "Na een hersenschudding kan het zenuwstelsel gevoeliger zijn. Prikkels zoals licht, geluid en beweging worden sneller als \u2018te veel\u2019 ervaren." },
          { type: "h3", text: "Nekklachten (cervicogene component)" },
          { type: "p", text: "De nek krijgt vaak een klap mee bij een val of botsing. Spanning of beperkte beweeglijkheid in de nek kan hoofdpijn en duizeligheid veroorzaken of in stand houden." },
          { type: "h3", text: "Kaakspanning en overbelasting" },
          { type: "p", text: "Veel mensen gaan onbewust hun kaak aanspannen bij stress of pijn. Dit kan leiden tot kaakklachten en hoofdpijn." },
          { type: "h3", text: "Evenwichts- en oogproblemen" },
          { type: "p", text: "Het evenwichtssysteem en de samenwerking met de ogen kunnen verstoord raken, wat duizeligheid en visuele klachten veroorzaakt." },
          { type: "h3", text: "Overbelasting en onderbelasting" },
          { type: "p", text: "Te snel weer te veel doen kan klachten verergeren, maar te weinig bewegen kan herstel ook vertragen. Het vinden van de juiste balans is essentieel." },
        ],
      },
      {
        id: "wanneer-hulp",
        title: "Wanneer is het verstandig om hulp te zoeken?",
        blocks: [
          { type: "p", text: "Het is normaal om na een hersenschudding tijdelijk klachten te hebben. Maar in de volgende situaties is het verstandig om hulp te zoeken:" },
          { type: "list", items: [
            "klachten houden langer dan 2\u20133 weken aan",
            "u merkt weinig tot geen verbetering",
            "hoofdpijn of duizeligheid neemt toe",
            "u heeft moeite met werk, studie of dagelijkse activiteiten",
            "u ervaart veel spanning in uw nek of kaak",
            "u voelt zich onzeker over uw herstel",
          ] },
          { type: "p", text: "Vroegtijdige begeleiding kan helpen om klachten niet chronisch te laten worden." },
        ],
      },
      {
        id: "hoe-helpt",
        title: "Hoe kan een orofaciaal fysiotherapeut helpen?",
        blocks: [
          { type: "p", text: "Een orofaciaal fysiotherapeut is gespecialiseerd in klachten in het hoofd-halsgebied, zoals kaakklachten, hoofdpijn en duizeligheid. Bij aanhoudende klachten na een hersenschudding wordt er breed gekeken naar alle factoren die een rol spelen." },
          { type: "h3", text: "Uitgebreid onderzoek" },
          { type: "p", text: "Tijdens de eerste afspraak wordt gekeken naar:" },
          { type: "list", items: [
            "uw klachten en het ontstaan ervan",
            "beweeglijkheid van de nek en kaak",
            "spierspanning in het hoofd-halsgebied",
            "houding en ademhaling",
            "evenwicht en co\u00f6rdinatie",
            "belasting en belastbaarheid in het dagelijks leven",
          ] },
          { type: "p", text: "Op basis hiervan wordt een persoonlijk behandelplan opgesteld." },
        ],
      },
      {
        id: "behandeling",
        title: "Behandeling in de praktijk",
        blocks: [
          { type: "p", text: "De behandeling is altijd afgestemd op uw klachten en hersteltempo. We werken stap voor stap aan het verbeteren van belastbaarheid en het verminderen van klachten." },
          { type: "h3", text: "Uitleg en begeleiding (educatie)" },
          { type: "p", text: "Inzicht in uw klachten is een belangrijke eerste stap. U leert hoe klachten ontstaan en in stand blijven, wat u zelf kunt doen om herstel te bevorderen en hoe u belasting en rust beter kunt afstemmen. Dit geeft vaak al rust en vertrouwen." },
          { type: "h3", text: "Oefentherapie" },
          { type: "p", text: "Gerichte oefeningen helpen om de nek en kaak te ontspannen en sterker te maken, het evenwicht en de co\u00f6rdinatie te verbeteren en het zenuwstelsel geleidelijk te laten wennen aan prikkels." },
          { type: "h3", text: "Manuele technieken" },
          { type: "p", text: "Indien nodig worden zachte mobilisaties toegepast om de beweeglijkheid van de nek te verbeteren, spierspanning te verminderen en hoofdpijnklachten te verlichten." },
          { type: "h3", text: "Kaaktraining" },
          { type: "p", text: "Bij kaakklachten of spanning wordt gewerkt aan bewustwording van kaakgebruik, ontspanningsoefeningen en het afleren van klemmen en knarsen." },
          { type: "h3", text: "Houdings- en ademhalingstraining" },
          { type: "p", text: "Een gespannen houding en oppervlakkige ademhaling kunnen klachten versterken. We werken aan een ontspannen houding en een rustige, effici\u00ebnte ademhaling." },
          { type: "h3", text: "Opbouw van belasting" },
          { type: "p", text: "Samen bouwen we activiteiten zoals werk, sport en schermgebruik geleidelijk weer op. Dit voorkomt overbelasting en helpt u vertrouwen terug te krijgen." },
        ],
      },
    ],
    faq: [
      { q: "Hoe lang duren klachten na een hersenschudding?", a: "De meeste mensen herstellen binnen 2–4 weken. Bij het postcommotioneel syndroom kunnen klachten langer aanhouden, maar met de juiste begeleiding verbeteren ze meestal geleidelijk." },
      { q: "Is het gevaarlijk dat mijn klachten blijven?", a: "Nee, aanhoudende klachten zijn vervelend maar meestal niet gevaarlijk. Ze wijzen vaak op een ontregeling, niet op blijvende schade." },
      { q: "Moet ik rust nemen of juist actief blijven?", a: "Beide zijn belangrijk. Volledige rust is meestal niet nodig, maar overbelasting moet worden voorkomen. Een goede balans is essentieel." },
      { q: "Kan stress mijn klachten verergeren?", a: "Ja, stress en spanning kunnen klachten zoals hoofdpijn en kaakspanning versterken. Daarom is aandacht voor ontspanning belangrijk." },
      { q: "Helpt fysiotherapie echt bij deze klachten?", a: "Ja, vooral wanneer nek, kaak, houding en belasting een rol spelen. Een gerichte aanpak kan klachten duidelijk verminderen." },
    ],
    closing: {
      title: "Herstel is mogelijk – ik help u graag verder",
      paragraphs: [
        "Blijven uw klachten aanhouden na een hersenschudding en merkt u dat dit uw dagelijks leven beïnvloedt? U hoeft hier niet mee te blijven rondlopen. Met een persoonlijke en rustige aanpak helpen we u om uw klachten beter te begrijpen en stap voor stap te verminderen.",
        "Neem gerust contact op voor advies of het maken van een afspraak.",
      ],
    },
  },
  {
    slug: "ademhalingsproblemen-hyperventilatie",
    name: "Ademhalingsproblemen & hyperventilatie",
    shortName: "Hyperventilatie",
    category: "klacht",
    seoTitle: "Hyperventilatie en ademhalingsklachten | Fysiotherapie",
    metaDescription:
      "Last van benauwdheid of hyperventilatie? Ontdek oorzaken, symptomen en hoe fysiotherapie helpt bij ademhalingsproblemen.",
    lead: "Het gevoel dat u niet goed kunt ademhalen?",
    card: "Benauwdheid, een opgejaagd gevoel of hyperventilatie zonder medische oorzaak — leer uw ademhaling weer reguleren.",
    sections: [
      {
        id: "introductie",
        title: "Het gevoel dat u niet goed kunt ademhalen?",
        blocks: [
          { type: "p", text: "Heeft u regelmatig het gevoel dat u niet goed kunt ademhalen? Of ervaart u benauwdheid, een opgejaagd gevoel of duizeligheid zonder duidelijke medische oorzaak? Dan kan er sprake zijn van ademhalingsproblemen of hyperventilatie." },
          { type: "p", text: "Veel mensen lopen hier langere tijd mee rond zonder precies te weten wat er aan de hand is. De klachten kunnen beangstigend zijn en invloed hebben op uw dagelijks functioneren. Een gespecialiseerde fysiotherapeut kan u helpen om uw ademhaling weer onder controle te krijgen en klachten te verminderen." },
        ],
      },
      {
        id: "wat-is-hyperventilatie",
        title: "Wat zijn ademhalingsproblemen en hyperventilatie?",
        blocks: [
          { type: "p", text: "Ademhalingsproblemen betekenen dat uw ademhaling niet optimaal verloopt. Dit kan te snel, te oppervlakkig of juist gespannen zijn." },
          { type: "p", text: "Hyperventilatie is een specifieke vorm van verkeerd ademen, waarbij u te snel of te diep ademt. Hierdoor raakt de balans tussen zuurstof en koolstofdioxide in uw lichaam verstoord. Dit kan allerlei lichamelijke klachten veroorzaken." },
          { type: "p", text: "Belangrijk om te weten: hyperventilatie is vervelend, maar niet gevaarlijk. Het lichaam kan het evenwicht weer herstellen, zeker met de juiste begeleiding." },
        ],
      },
      {
        id: "symptomen",
        title: "Symptomen van ademhalingsproblemen en hyperventilatie",
        blocks: [
          { type: "p", text: "De klachten kunnen per persoon verschillen en zijn soms moeilijk te herkennen als ademhalingsprobleem." },
          { type: "h3", text: "Lichamelijke klachten" },
          { type: "list", items: [
            "benauwd gevoel of \u201cniet diep genoeg kunnen ademhalen\u201d",
            "duizeligheid of licht gevoel in het hoofd",
            "hartkloppingen",
            "tintelingen in handen, voeten of rond de mond",
            "druk op de borst",
            "vermoeidheid",
          ] },
          { type: "h3", text: "Spanning en stressgerelateerde klachten" },
          { type: "list", items: ["onrustig of opgejaagd gevoel", "moeite met ontspannen", "angstklachten of paniekgevoelens"] },
          { type: "h3", text: "Klachten in het hoofd-halsgebied" },
          { type: "list", items: ["spanning in nek en schouders", "hoofdpijn", "kaakspanning", "duizeligheidsklachten"] },
          { type: "p", text: "Deze klachten kunnen elkaar versterken, waardoor een vicieuze cirkel ontstaat." },
        ],
      },
      {
        id: "oorzaken",
        title: "Mogelijke oorzaken",
        blocks: [
          { type: "p", text: "Ademhalingsproblemen en hyperventilatie ontstaan vaak door een combinatie van factoren." },
          { type: "h3", text: "Stress en spanning" },
          { type: "p", text: "De meest voorkomende oorzaak. Bij stress gaat u automatisch sneller en hoger ademen." },
          { type: "h3", text: "Verkeerde ademgewoonten" },
          { type: "list", items: ["hoog in de borst ademen", "te vaak zuchten of diep inademen", "onbewust de adem inhouden"] },
          { type: "h3", text: "Lichamelijke factoren" },
          { type: "list", items: ["nek-, hoofd- en schouderklachten", "duizeligheid", "houdingsproblemen", "verminderde conditie"] },
          { type: "h3", text: "Andere invloeden" },
          { type: "list", items: ["angst- of paniekklachten", "drukke levensstijl", "slechte slaapkwaliteit"] },
          { type: "p", text: "Vaak is het geen bewuste keuze, maar een patroon dat zich geleidelijk ontwikkelt." },
        ],
      },
      {
        id: "wanneer-hulp",
        title: "Wanneer is het verstandig om hulp te zoeken?",
        blocks: [
          { type: "p", text: "Het is goed om hulp te zoeken als:" },
          { type: "list", items: [
            "u regelmatig last heeft van benauwdheid of hyperventilatie",
            "klachten zoals duizeligheid of hartkloppingen blijven terugkomen",
            "u merkt dat stress uw ademhaling be\u00efnvloedt",
            "u onzeker wordt over uw lichaam of bang bent voor de klachten",
            "medisch onderzoek geen duidelijke oorzaak geeft",
          ] },
          { type: "p", text: "Begeleiding helpt om inzicht te krijgen in uw ademhaling en om klachten effectief aan te pakken." },
        ],
      },
      {
        id: "hoe-helpt",
        title: "Hoe kan een orofaciaal fysiotherapeut helpen?",
        blocks: [
          { type: "p", text: "Een orofaciaal fysiotherapeut kijkt niet alleen naar de ademhaling, maar ook naar het hoofd-halsgebied, waar veel spanning samenkomt." },
          { type: "h3", text: "Onderzoek" },
          { type: "p", text: "Tijdens het onderzoek wordt gekeken naar:" },
          { type: "list", items: [
            "uw ademhalingspatroon",
            "gebruik van borst- en buikademhaling",
            "spierspanning in nek, schouders en kaak",
            "houding en bewegingsgedrag",
            "invloed van stress en spanning",
          ] },
          { type: "h3", text: "Inzicht en bewustwording" },
          { type: "p", text: "U leert herkennen wanneer uw ademhaling verandert, wat uw triggers zijn en hoe u spanning opbouwt. Dit is een belangrijke eerste stap naar herstel." },
        ],
      },
      {
        id: "behandeling",
        title: "Behandeling in de praktijk",
        blocks: [
          { type: "p", text: "De behandeling is gericht op het herstellen van een rustige, natuurlijke ademhaling en het verminderen van klachten." },
          { type: "h3", text: "Ademhalingsoefeningen" },
          { type: "list", items: ["aanleren van buikademhaling", "vertragen van de ademhaling", "oefeningen voor ontspanning"] },
          { type: "h3", text: "Spierontspanning" },
          { type: "list", items: ["verminderen van spanning in nek en schouders", "ontspanning van kaakspieren", "bewust leren loslaten van spanning"] },
          { type: "h3", text: "Houdingsadvies" },
          { type: "list", items: ["verbeteren van zithouding en werkhouding", "optimaliseren van ademruimte", "voorkomen van overbelasting"] },
          { type: "h3", text: "Stressregulatie" },
          { type: "list", items: ["herkennen van stresssignalen", "praktische tips om spanning te verminderen", "opbouwen van balans tussen belasting en herstel"] },
          { type: "h3", text: "Opbouw van vertrouwen" },
          { type: "p", text: "Veel mensen raken onzeker door hun klachten. Daarom werken we ook aan vertrouwen in het lichaam, het verminderen van angst voor klachten en een geleidelijke opbouw van activiteiten. De behandeling is altijd afgestemd op uw persoonlijke situatie." },
        ],
      },
    ],
    faq: [
      { q: "Is hyperventilatie gevaarlijk?", a: "Nee, het is niet gevaarlijk. De klachten kunnen heftig aanvoelen, maar uw lichaam herstelt de balans vanzelf." },
      { q: "Kan ik er vanaf komen?", a: "Ja, met de juiste begeleiding en oefeningen kunnen de klachten sterk verminderen of verdwijnen." },
      { q: "Moet ik anders gaan ademen?", a: "Ja, maar op een ontspannen manier. Het gaat niet om \u201cgoed presteren\u201d, maar om een natuurlijk ademritme." },
      { q: "Helpt fysiotherapie echt?", a: "Zeker. Fysiotherapie richt zich op inzicht en kennis, het doorbreken van verkeerde ademhalingspatronen en het verminderen van spanning." },
      { q: "Kan stress de enige oorzaak zijn?", a: "Stress speelt vaak een grote rol, maar meestal is het een combinatie van factoren." },
    ],
    closing: {
      title: "Herkent u deze klachten?",
      paragraphs: [
        "Ademhalingsproblemen en hyperventilatie kunnen een grote impact hebben op hoe u zich voelt, zowel lichamelijk als mentaal. Met gerichte begeleiding leert u uw ademhaling weer onder controle te krijgen en spanning los te laten. Dit zorgt vaak voor meer rust, energie en vertrouwen in uw lichaam.",
        "Herkent u uw klachten in dit verhaal? Neem gerust contact op voor advies of een afspraak. Samen kijken we naar een passende oplossing voor uw situatie.",
      ],
    },
  },
  {
    slug: "act-chronische-pijn-kaakfysiotherapie",
    name: "ACT bij chronische pijn",
    shortName: "ACT bij chronische pijn",
    category: "behandelvorm",
    seoTitle: "ACT bij chronische pijn | Orofaciale fysiotherapie",
    metaDescription:
      "Leer hoe ACT helpt bij chronische pijn in hoofd en kaak. Praktische uitleg en behandeling door gespecialiseerde fysiotherapeut.",
    lead: "Chronische pijn: meer dan alleen een lichamelijk probleem.",
    card: "Acceptance and Commitment Therapy als onderdeel van de behandeling bij aanhoudende pijn in het hoofd-halsgebied.",
    sections: [
      {
        id: "introductie",
        title: "Chronische pijn: meer dan alleen een lichamelijk probleem",
        blocks: [
          { type: "p", text: "Blijvende pijnklachten in het hoofd-halsgebied kunnen een grote invloed hebben op uw dagelijks leven. Denk aan kaakpijn, hoofdpijn, aangezichtspijn of een constant gespannen gevoel in de nek. Vaak heeft u al van alles geprobeerd, maar blijven de klachten aanwezig." },
          { type: "p", text: "Chronische pijn is complex. Het gaat niet alleen om wat er in het lichaam gebeurt, maar ook om hoe u met de pijn omgaat, wat u denkt en voelt, en hoe dit uw gedrag be\u00efnvloedt. Juist daarom kan een bredere aanpak nodig zijn." },
          { type: "p", text: "Binnen de orofaciale fysiotherapie wordt steeds vaker gewerkt met ACT (Acceptance and Commitment Therapy). Deze methode helpt u anders om te gaan met pijn, zodat deze minder grip krijgt op uw leven." },
        ],
      },
      {
        id: "wat-is-act",
        title: "Wat is ACT?",
        blocks: [
          { type: "p", text: "ACT is een behandelvorm die zich richt op het vergroten van psychologische flexibiliteit. Dat betekent: leren omgaan met moeilijke gedachten, gevoelens en pijnklachten, zonder dat ze uw leven volledig bepalen." },
          { type: "p", text: "In plaats van de pijn direct te willen \u201coplossen\u201d of weg te nemen, richt ACT zich op:" },
          { type: "list", items: [
            "het accepteren van wat u op dit moment ervaart",
            "het verminderen van de strijd tegen de pijn",
            "het vergroten van wat voor u \u00e9cht belangrijk is in het leven",
          ] },
          { type: "p", text: "Bij chronische klachten, zoals langdurige kaakpijn of hoofdpijn, kan het voortdurend proberen te controleren of vermijden van pijn juist averechts werken. ACT helpt u om die vicieuze cirkel te doorbreken." },
          { type: "h3", text: "ACT in het kort" },
          { type: "list", items: [
            "Acceptance (acceptatie): ruimte maken voor pijn en ongemak",
            "Commitment (toewijding): keuzes maken die passen bij uw waarden",
            "Focus op gedrag: wat doet u ondanks de pijn?",
          ] },
          { type: "p", text: "Dit betekent niet dat de pijn \u201ctussen uw oren zit\u201d. Het betekent dat u leert hoe u ermee omgaat, zodat u meer regie krijgt over uw dagelijks functioneren." },
        ],
      },
      {
        id: "wanneer-hulp",
        title: "Wanneer is het verstandig om hulp te zoeken?",
        blocks: [
          { type: "p", text: "Het is niet altijd eenvoudig om te bepalen wanneer professionele hulp nodig is. Toch zijn er duidelijke signalen waarbij ACT binnen de fysiotherapie zinvol kan zijn." },
          { type: "h3", text: "Herkenbare klachten" },
          { type: "list", items: [
            "u heeft langdurige pijn in kaak, gezicht, hoofd of nek",
            "de klachten zijn al weken tot maanden aanwezig",
            "behandelingen hebben tot nu toe onvoldoende effect gehad",
            "u merkt dat de pijn uw dagelijks functioneren be\u00efnvloedt",
            "u bent veel bezig met de pijn of maakt zich er zorgen over",
          ] },
          { type: "h3", text: "Gedrag en impact" },
          { type: "list", items: [
            "u vermijdt bepaalde bewegingen of activiteiten uit angst voor pijn",
            "u voelt zich gespannen, gefrustreerd of somber door de klachten",
            "u heeft moeite om te ontspannen in het hoofd-halsgebied",
            "de klachten be\u00efnvloeden uw werk, slaap of sociale leven",
          ] },
          { type: "p", text: "Juist als pijnklachten complexer worden, kan een combinatie van lichamelijke en gedragsgerichte behandeling \u2013 zoals ACT \u2013 een waardevolle stap zijn." },
        ],
      },
      {
        id: "hoe-helpt",
        title: "Hoe kan een orofaciaal fysiotherapeut helpen?",
        blocks: [
          { type: "p", text: "Een orofaciaal fysiotherapeut is gespecialiseerd in klachten van het hoofd-halsgebied, zoals kaakklachten (TMD), aangezichtspijn, hoofdpijn, spierspanning in nek en kaak en duizeligheidsklachten. Bij chronische pijn kijkt de therapeut verder dan alleen de spieren en gewrichten." },
          { type: "h3", text: "Onderzoek" },
          { type: "p", text: "Tijdens de eerste afspraak wordt uitgebreid gekeken naar:" },
          { type: "list", items: [
            "uw klachten en het beloop",
            "spierspanning en beweeglijkheid",
            "kaakfunctie en houding",
            "invloed van stress en gewoontes",
            "uw manier van omgaan met de pijn",
          ] },
          { type: "p", text: "Dit geeft een compleet beeld van de factoren die uw klachten in stand houden." },
          { type: "h3", text: "Behandeling" },
          { type: "p", text: "De behandeling bestaat vaak uit een combinatie van uitleg over pijn en het zenuwstelsel, oefeningen voor ontspanning en controle, advies over houding en belasting, en gedragsmatige begeleiding met ACT. Het doel is niet alleen minder pijn, maar vooral beter functioneren ondanks de pijn." },
        ],
      },
      {
        id: "behandeling",
        title: "ACT als onderdeel van fysiotherapie",
        blocks: [
          { type: "p", text: "In de praktijk wordt ACT ge\u00efntegreerd in de behandeling van chronische klachten in het hoofd-halsgebied. De behandeling is praktisch, persoonlijk en afgestemd op uw situatie." },
          { type: "h3", text: "Inzicht in uw klachten" },
          { type: "p", text: "U leert hoe pijn werkt en waarom deze soms blijft bestaan. Dit helpt om angst en onzekerheid te verminderen." },
          { type: "h3", text: "Anders leren omgaan met pijn" },
          { type: "p", text: "Samen onderzoeken we welke gedachten u heeft over de pijn, hoe deze uw gedrag be\u00efnvloeden en welke patronen mogelijk klachten in stand houden. U leert om hier op een andere, meer helpende manier mee om te gaan." },
          { type: "h3", text: "Gericht op wat belangrijk is" },
          { type: "p", text: "We kijken naar wat voor u belangrijk is in het leven, zoals werk, hobby\u2019s of sociale contacten. Vervolgens werken we stap voor stap toe naar herstel van deze activiteiten." },
          { type: "h3", text: "Praktische oefeningen" },
          { type: "list", items: [
            "ademhalings- en ontspanningsoefeningen",
            "aandachtsoefeningen (mindfulness)",
            "oefeningen voor kaak en nek",
            "opbouw van belastbaarheid",
          ] },
          { type: "h3", text: "Het doel" },
          { type: "p", text: "Het doel van ACT binnen fysiotherapie is niet alleen pijnvermindering, maar vooral meer controle over uw leven, minder beperkingen in het dagelijks functioneren en meer vertrouwen in uw lichaam." },
        ],
      },
    ],
    faq: [
      { q: "Werkt ACT ook als mijn pijn niet overgaat?", a: "Ja. ACT richt zich juist op situaties waarin pijn langdurig aanwezig blijft. U leert beter functioneren ondanks de klachten." },
      { q: "Betekent acceptatie dat ik moet leren leven met pijn?", a: "Acceptatie betekent niet opgeven. Het betekent stoppen met de constante strijd tegen pijn, zodat u energie kunt steken in wat echt belangrijk is." },
      { q: "Is ACT hetzelfde als psychologie?", a: "ACT komt uit de psychologie, maar wordt binnen de fysiotherapie praktisch toegepast en gekoppeld aan lichamelijke klachten en beweging." },
      { q: "Hoe lang duurt een behandeling?", a: "Dit verschilt per persoon. U volgt een online module met lessen die u vanuit huis doet; deze worden in de behandeling kort besproken. Vaak zijn meerdere sessies nodig om nieuwe vaardigheden aan te leren en toe te passen in het dagelijks leven." },
      { q: "Wordt ACT vergoed?", a: "Orofaciale fysiotherapie valt vaak (deels) onder de aanvullende verzekering. Dit hangt af van uw polis." },
    ],
    closing: {
      title: "Neem de eerste stap naar meer grip op uw klachten",
      paragraphs: [
        "Blijft u last houden van chronische pijn in het hoofd-halsgebied? En merkt u dat dit uw dagelijks leven beïnvloedt? Dan kan een behandeling met ACT binnen de orofaciale fysiotherapie u helpen om weer meer controle en vertrouwen te krijgen. U hoeft hier niet mee te blijven rondlopen.",
        "Neem gerust contact op voor meer informatie of het maken van een afspraak. Samen kijken we naar wat u nodig heeft om weer beter te kunnen functioneren.",
      ],
    },
  },
];
