import type { Klacht } from "./types";

export const klachten1: Klacht[] = [
  {
    slug: "kaakklachten-tmd",
    name: "Kaakklachten (TMD)",
    shortName: "Kaakklachten (TMD)",
    category: "klacht",
    seoTitle: "Kaakklachten (TMD) – Oorzaken, symptomen en behandeling",
    metaDescription:
      "Last van kaakpijn, knakken of hoofdpijn? Lees alles over TMD-klachten en hoe een orofaciaal fysiotherapeut kan helpen.",
    lead: "Pijn of spanning in de kaak? U bent niet de enige.",
    card: "Pijn, knakken of spanning rond het kaakgewricht en de kauwspieren, vaak samen met hoofdpijn of oorklachten.",
    sections: [
      {
        id: "introductie",
        title: "Pijn of spanning in de kaak? U bent niet de enige",
        blocks: [
          { type: "p", text: "Veel mensen hebben weleens last van hun kaak zonder precies te weten waar het vandaan komt. Misschien voelt uw kaak vermoeid na het praten of eten, hoort u een knak bij het openen van de mond, of ervaart u pijn rondom het kaakgewricht. Ook klachten zoals hoofdpijn, oorpijn of spanning in het gezicht kunnen hiermee samenhangen." },
          { type: "p", text: "Deze klachten vallen vaak onder de verzamelnaam TMD (Temporomandibulaire Dysfunctie). Het gaat hierbij om problemen in het kaakgewricht, de kauwspieren of de manier waarop de kaak beweegt." },
          { type: "p", text: "Een orofaciaal fysiotherapeut, ook wel kaakfysiotherapeut genoemd, is gespecialiseerd in het onderzoeken en behandelen van klachten in het hoofd-halsgebied. Met de juiste begeleiding kunnen veel mensen hun klachten aanzienlijk verminderen of zelfs volledig herstellen." },
        ],
      },
      {
        id: "wat-is-tmd",
        title: "Wat zijn TMD-klachten?",
        blocks: [
          { type: "p", text: "TMD staat voor Temporomandibulaire Dysfunctie. Dat betekent dat er een probleem is in het kaakgewricht, de kauwspieren of de samenwerking tussen beide." },
          { type: "p", text: "Het kaakgewricht is een complex gewricht dat zich vlak voor het oor bevindt. Het zorgt ervoor dat u uw mond kunt openen en sluiten, kunt praten, kauwen en slikken. Bij elke hap en elk woord werken verschillende spieren en structuren nauw samen." },
          { type: "p", text: "Wanneer deze samenwerking verstoord raakt, kunnen klachten ontstaan. Soms gaat het om tijdelijke overbelasting, maar bij andere mensen houden de klachten langer aan." },
          { type: "p", text: "TMD-klachten komen relatief vaak voor. Veel mensen ervaren ze in milde vorm, maar bij sommigen kunnen ze invloed hebben op dagelijkse activiteiten zoals eten, praten of slapen." },
        ],
      },
      {
        id: "symptomen",
        title: "Symptomen van TMD-klachten",
        blocks: [
          { type: "p", text: "Kaakklachten kunnen zich op verschillende manieren uiten. Sommige symptomen zijn duidelijk gelokaliseerd in de kaak, terwijl andere klachten zich in het hoofd-halsgebied voordoen." },
          { type: "h3", text: "Pijn rondom de kaak" },
          { type: "p", text: "Pijn kan gevoeld worden in:" },
          { type: "list", items: ["het kaakgewricht", "de kauwspieren", "het gebied rondom of in het oor", "de wang of slaap", "tanden of kiezen"] },
          { type: "p", text: "De pijn kan verergeren bij kauwen, praten, geeuwen of het openen van de mond." },
          { type: "h3", text: "Knakken of klikken van de kaak" },
          { type: "p", text: "Sommige mensen horen of voelen een klik of knak bij het openen of sluiten van de mond. Dit kan ontstaan wanneer de structuren in het kaakgewricht anders bewegen dan normaal. Vaak is dit onschuldig, maar wanneer het gepaard gaat met pijn of beperkingen kan behandeling zinvol zijn." },
          { type: "h3", text: "Beperkte mondopening" },
          { type: "p", text: "Bij sommige mensen wordt het moeilijk om de mond wijd te openen. Dit kan bijvoorbeeld merkbaar zijn bij het eten van een grote hap, gapen of een tandartsbezoek. Soms kan de kaak zelfs tijdelijk \u201cop slot\u201d raken." },
          { type: "h3", text: "Hoofdpijn en spanningsklachten" },
          { type: "p", text: "TMD kan ook leiden tot:" },
          { type: "list", items: ["hoofdpijn (vooral bij de slapen)", "spanning in het gezicht", "pijn in de nek of schouders"] },
          { type: "p", text: "Deze klachten ontstaan vaak door overbelasting van de kauwspieren." },
          { type: "h3", text: "Andere mogelijke klachten" },
          { type: "list", items: ["vermoeid gevoel in de kaak", "pijn bij kauwen", "oorpijn zonder oorontsteking", "gevoel van druk rond het oor", "tandenknarsen of klemmen"] },
          { type: "p", text: "Omdat deze klachten ook andere oorzaken kunnen hebben, is een goede beoordeling belangrijk." },
        ],
      },
      {
        id: "oorzaken",
        title: "Mogelijke oorzaken van TMD",
        blocks: [
          { type: "p", text: "TMD-klachten ontstaan meestal niet door \u00e9\u00e9n enkele oorzaak. Vaak spelen meerdere factoren tegelijk een rol." },
          { type: "h3", text: "Overbelasting van de kauwspieren" },
          { type: "p", text: "Een veelvoorkomende oorzaak is spierspanning door tandenknarsen (bruxisme), klemmen van de kaken of langdurige stress en spanning. Hierdoor raken de spieren rondom de kaak overbelast." },
          { type: "h3", text: "Problemen in het kaakgewricht" },
          { type: "p", text: "Soms ligt de oorzaak in het gewricht zelf, bijvoorbeeld een verplaatsing van de discus (een soort schijfje in het gewricht), irritatie of ontsteking van het gewricht, of verminderde beweeglijkheid van de kaak. Dit kan leiden tot pijn, knakken of een beperkte mondopening." },
          { type: "h3", text: "Stress en spanning" },
          { type: "p", text: "Stress kan een belangrijke rol spelen bij kaakklachten. Veel mensen klemmen onbewust hun tanden of spannen hun kaakspieren aan tijdens concentratie of spanning. Dit kan vooral \u2019s nachts of tijdens werk voorkomen." },
          { type: "h3", text: "Houding en nekklachten" },
          { type: "p", text: "De stand van het hoofd en de nek heeft invloed op de kaak. Een langdurige voorovergebogen houding (bijvoorbeeld bij computerwerk) kan bijdragen aan spanning in het hoofd-halsgebied." },
          { type: "h3", text: "Trauma of overbelasting" },
          { type: "p", text: "Ook kunnen klachten ontstaan na:" },
          { type: "list", items: ["een val of ongeluk", "langdurig kauwen (bijvoorbeeld kauwgom)", "een langdurige tandartsbehandeling", "een periode van intensief praten of zingen"] },
        ],
      },
      {
        id: "wanneer-hulp",
        title: "Wanneer is het verstandig om hulp te zoeken?",
        blocks: [
          { type: "p", text: "Veel kaakklachten verdwijnen vanzelf binnen enkele weken. Toch kan het verstandig zijn om een specialist te raadplegen wanneer klachten langer aanhouden. Neem bijvoorbeeld contact op als u:" },
          { type: "list", items: [
            "langer dan enkele weken pijn heeft in de kaak",
            "moeite heeft met het openen van de mond",
            "regelmatig hoofdpijn of gezichtspijn ervaart",
            "een knak of klik in de kaak heeft met pijn",
            "merkt dat u veel klemt of knarst",
            "problemen heeft met kauwen of praten",
            "onverklaarbare tand- of kiespijn heeft",
          ] },
          { type: "p", text: "Een vroege beoordeling kan helpen om klachten sneller te verminderen en verdere overbelasting te voorkomen." },
        ],
      },
      {
        id: "hoe-helpt",
        title: "Hoe kan een orofaciaal fysiotherapeut helpen?",
        blocks: [
          { type: "p", text: "Een orofaciaal fysiotherapeut is gespecialiseerd in klachten van het gezicht, hoofd, kaak en nek. Tijdens het eerste consult wordt uitgebreid gekeken naar:" },
          { type: "list", items: [
            "uw klachten en medische voorgeschiedenis",
            "het functioneren van de kaak",
            "de beweeglijkheid van het kaakgewricht",
            "de spanning van de kauwspieren",
            "de houding van hoofd en nek",
          ] },
          { type: "p", text: "Ook wordt gekeken naar factoren zoals stress, klemgedrag en dagelijkse belasting van de kaak. Op basis van dit onderzoek wordt een persoonlijk behandelplan opgesteld." },
        ],
      },
      {
        id: "behandeling",
        title: "Behandeling van kaakklachten in de praktijk",
        blocks: [
          { type: "p", text: "De behandeling van TMD richt zich meestal op het verminderen van pijn, het herstellen van normale kaakbeweging en het voorkomen van overbelasting. Afhankelijk van uw klachten kan de behandeling bestaan uit verschillende onderdelen." },
          { type: "h3", text: "Uitleg en advies" },
          { type: "p", text: "Inzicht in uw klacht is een belangrijk onderdeel van herstel. U krijgt uitleg over hoe het kaakgewricht werkt, welke factoren uw klachten be\u00efnvloeden en hoe u overbelasting kunt voorkomen. Praktische adviezen kunnen bijvoorbeeld gaan over kauwgedrag, rustmomenten voor de kaak en het verminderen van klemmen." },
          { type: "h3", text: "Oefentherapie en kaaktraining" },
          { type: "p", text: "Gerichte oefeningen helpen om de kauwspieren te ontspannen, de beweeglijkheid van de kaak te verbeteren en een gezond bewegingspatroon aan te leren. Bij klem- of knarsgedrag werkt u aan bewustwording en het aanleren van een ontspannen kaakhouding." },
          { type: "h3", text: "Manuele technieken" },
          { type: "p", text: "De fysiotherapeut kan verschillende technieken gebruiken om pijn en spanning te verminderen, zoals mobilisaties van het kaakgewricht en de nek en behandeling van gespannen kauwspieren." },
          { type: "h3", text: "Houdings- en leefstijladvies" },
          { type: "p", text: "Omdat houding en dagelijkse gewoonten invloed hebben op de kaak, is er waar nodig aandacht voor werkhouding, schermgebruik en de balans tussen belasting en herstel." },
        ],
      },
    ],
    faq: [
      { q: "Is een knakkende kaak gevaarlijk?", a: "Meestal niet. Een knak of klik zonder pijn is vaak onschuldig. Wanneer het knakken samengaat met pijn of een beperkte mondopening, is het verstandig om dit te laten beoordelen." },
      { q: "Kan stress kaakklachten veroorzaken?", a: "Ja. Veel mensen klemmen of knarsen onbewust bij stress of concentratie, waardoor de kauwspieren overbelast raken. Dit kan pijn en hoofdpijn veroorzaken." },
      { q: "Helpt fysiotherapie bij kaakklachten?", a: "Ja, vooral bij spier- en gewrichtsgerelateerde klachten is orofaciale fysiotherapie vaak effectief. De behandeling richt zich op pijnvermindering en herstel van normale kaakfunctie." },
      { q: "Hoe lang duurt herstel van TMD-klachten?", a: "Dit verschilt per persoon. Sommige mensen merken al binnen enkele behandelingen verbetering, terwijl langdurige klachten meer tijd nodig hebben." },
      { q: "Moet ik naar de tandarts of de fysiotherapeut?", a: "Beide kunnen een rol spelen. Waar nodig wordt samengewerkt met tandarts, kaakchirurg of andere zorgverleners om de best passende zorg te bieden." },
    ],
    closing: {
      title: "Blijft u last houden van uw kaak?",
      paragraphs: [
        "Kaakklachten kunnen een grote invloed hebben op eten, praten en ontspannen. Gelukkig zijn veel TMD-klachten goed te behandelen wanneer de onderliggende oorzaak wordt aangepakt.",
        "Neem gerust contact op voor advies of het maken van een afspraak. Samen kijken we naar de oorzaak van uw klachten en naar een behandeling die past bij uw situatie.",
      ],
    },
  },
  {
    slug: "hoofdpijn-behandeling-fysiotherapie",
    name: "Hoofdpijn",
    shortName: "Hoofdpijn",
    category: "klacht",
    seoTitle: "Hoofdpijn behandelen – hulp van de orofaciaal fysiotherapeut",
    metaDescription:
      "Last van hoofdpijn? Lees oorzaken, symptomen en hoe een orofaciaal fysiotherapeut kan helpen bij spanningshoofdpijn en kaakgerelateerde klachten.",
    lead: "Regelmatig hoofdpijn? U bent niet de enige.",
    card: "Spanningshoofdpijn, hoofdpijn vanuit de nek of hoofdpijn die samenhangt met kaakspanning en klemgedrag.",
    sections: [
      {
        id: "introductie",
        title: "Regelmatig hoofdpijn? U bent niet de enige",
        blocks: [
          { type: "p", text: "Veel mensen hebben weleens last van hoofdpijn. Soms is het een lichte druk aan het einde van een drukke dag, maar bij anderen komt de pijn regelmatig terug of blijft deze langer aanwezig. Hoofdpijn kan invloed hebben op werk, concentratie, slaap en dagelijkse activiteiten." },
          { type: "p", text: "Veel mensen denken bij hoofdpijn niet direct aan fysiotherapie. Toch kunnen spieren en gewrichten in de nek, kaak en het hoofd-halsgebied een belangrijke rol spelen bij het ontstaan van hoofdpijnklachten." },
          { type: "p", text: "Een orofaciaal fysiotherapeut is gespecialiseerd in klachten van het gezicht, de kaak, het hoofd en de nek. Door gericht onderzoek kan vaak duidelijk worden waar de hoofdpijn vandaan komt en welke behandeling kan helpen om de klachten te verminderen." },
        ],
      },
      {
        id: "wat-is-hoofdpijn",
        title: "Wat is hoofdpijn?",
        blocks: [
          { type: "p", text: "Hoofdpijn is een verzamelnaam voor pijnklachten in of rondom het hoofd. De pijn kan op verschillende plekken voorkomen, bijvoorbeeld:" },
          { type: "list", items: ["bij de slapen", "rondom de ogen", "in het voorhoofd", "achter in het hoofd", "in de nek, doorstralend naar het hoofd"] },
          { type: "p", text: "Er bestaan verschillende vormen van hoofdpijn. Veelvoorkomende typen zijn:" },
          { type: "list", items: ["spanningshoofdpijn", "hoofdpijn vanuit de nek (cervicogene hoofdpijn)", "hoofdpijn gerelateerd aan kaakklachten (TMD)", "migraine"] },
          { type: "p", text: "Bij sommige vormen spelen spieren, gewrichten of houding een belangrijke rol. In die gevallen kan fysiotherapie een zinvolle behandeling zijn. Hoofdpijn ontstaat vaak door een combinatie van factoren. Daarom is het belangrijk om goed te kijken naar het hele hoofd-halsgebied en naar dagelijkse gewoonten die de klachten kunnen be\u00efnvloeden." },
        ],
      },
      {
        id: "symptomen",
        title: "Symptomen van hoofdpijn",
        blocks: [
          { type: "p", text: "Hoofdpijn kan zich op verschillende manieren uiten. De aard en intensiteit van de pijn verschilt per persoon en per type hoofdpijn." },
          { type: "h3", text: "Drukkende of knellende pijn" },
          { type: "p", text: "Veel mensen met spanningshoofdpijn beschrijven de pijn als een drukkend of strak gevoel rondom het hoofd. Het voelt soms alsof er een band om het hoofd zit. Deze pijn kan uren tot dagen aanhouden." },
          { type: "h3", text: "Pijn vanuit de nek" },
          { type: "p", text: "Bij sommige mensen begint de pijn in de nek of achter in het hoofd en trekt deze naar voren richting het voorhoofd of de slapen. Dit kan bijvoorbeeld verergeren bij:" },
          { type: "list", items: ["langdurig computerwerk", "een verkeerde houding", "spanning in de nekspieren"] },
          { type: "h3", text: "Pijn bij de slapen of kaak" },
          { type: "p", text: "Hoofdpijn kan ook samenhangen met spanning in de kauwspieren of problemen in het kaakgewricht. Mensen ervaren dan bijvoorbeeld:" },
          { type: "list", items: ["pijn bij de slapen", "vermoeidheid van de kaak", "hoofdpijn bij kauwen of praten", "tandenknarsen of klemmen"] },
          { type: "h3", text: "Andere mogelijke klachten" },
          { type: "p", text: "Hoofdpijn kan ook samengaan met:" },
          { type: "list", items: ["gevoeligheid van de hoofdhuid", "nekpijn of een stijve nek", "vermoeidheid", "concentratieproblemen", "drukgevoel achter de ogen"] },
          { type: "p", text: "Omdat hoofdpijn verschillende oorzaken kan hebben, is het belangrijk om goed te onderzoeken wat de klachten be\u00efnvloedt." },
        ],
      },
      {
        id: "oorzaken",
        title: "Mogelijke oorzaken van hoofdpijn",
        blocks: [
          { type: "p", text: "Hoofdpijn ontstaat vaak door een combinatie van lichamelijke en leefstijlfactoren." },
          { type: "h3", text: "Spierspanning in nek en schouders" },
          { type: "p", text: "Een veelvoorkomende oorzaak van hoofdpijn is spierspanning in de nek, schouders en het hoofd-halsgebied. Dit kan ontstaan door:" },
          { type: "list", items: ["langdurig beeldschermwerk", "een statische houding", "stress of spanning", "weinig beweging"] },
          { type: "p", text: "De gespannen spieren kunnen pijn veroorzaken die uitstraalt naar het hoofd." },
          { type: "h3", text: "Kaakklachten en tandenknarsen" },
          { type: "p", text: "Veel mensen klemmen onbewust hun kaken, bijvoorbeeld tijdens stress of concentratie. Dit kan leiden tot overbelasting van de kauwspieren. Hierdoor kan hoofdpijn ontstaan, vaak rond de slapen of het voorhoofd." },
          { type: "h3", text: "Nekproblemen" },
          { type: "p", text: "Beperkte beweeglijkheid van de nekgewrichten of spanning in de nekspieren kan ook hoofdpijn veroorzaken. Dit wordt cervicogene hoofdpijn genoemd. De pijn begint vaak in de nek en straalt uit naar het hoofd." },
          { type: "h3", text: "Stress, vermoeidheid en houding" },
          { type: "p", text: "Stress speelt bij veel mensen een rol bij hoofdpijn. Spanning kan leiden tot verhoogde spierspanning en veranderingen in ademhaling en houding. Ook langdurig voorovergebogen werken, bijvoorbeeld achter een laptop of telefoon, kan de belasting op de nek en het hoofd vergroten." },
        ],
      },
      {
        id: "wanneer-hulp",
        title: "Wanneer is het verstandig om hulp te zoeken?",
        blocks: [
          { type: "p", text: "Hoofdpijn komt veel voor en is meestal onschuldig. Toch kan het verstandig zijn om hulp te zoeken wanneer de klachten regelmatig terugkomen of invloed hebben op uw dagelijks leven. Overweeg om een specialist te raadplegen wanneer:" },
          { type: "list", items: [
            "de hoofdpijn regelmatig terugkomt",
            "de klachten langer dan enkele weken aanhouden",
            "u daarnaast nek- of kaakklachten heeft",
            "de pijn verergert bij het bewegen van de nek of kaak",
            "hoofdpijn invloed heeft op werk, slaap of concentratie",
            "pijnstillers vaak nodig zijn om de klachten te verminderen",
          ] },
          { type: "p", text: "Een goede beoordeling kan helpen om de oorzaak van de klachten beter te begrijpen." },
        ],
      },
      {
        id: "hoe-helpt",
        title: "Hoe kan een orofaciaal fysiotherapeut helpen?",
        blocks: [
          { type: "p", text: "Een orofaciaal fysiotherapeut is gespecialiseerd in klachten van het hoofd, gezicht, kaak en nek. Tijdens het eerste consult wordt uitgebreid gekeken naar:" },
          { type: "list", items: ["uw klachten en medische voorgeschiedenis", "wanneer de hoofdpijn optreedt", "mogelijke uitlokkende factoren", "houding tijdens werk en dagelijkse activiteiten"] },
          { type: "p", text: "Daarnaast wordt lichamelijk onderzoek gedaan, zoals:" },
          { type: "list", items: ["onderzoek van de nekgewrichten", "beoordeling van spierspanning in nek en schouders", "onderzoek van de kauwspieren", "onderzoek van het kaakgewricht", "beoordeling van houding en beweging"] },
          { type: "p", text: "Met deze informatie kan worden bepaald welke factoren bijdragen aan uw hoofdpijnklachten." },
        ],
      },
      {
        id: "behandeling",
        title: "Behandeling van hoofdpijn in de praktijk",
        blocks: [
          { type: "p", text: "De behandeling van hoofdpijn richt zich meestal op het verminderen van pijn, het verbeteren van de functie van spieren en gewrichten en het voorkomen van overbelasting. De behandeling wordt afgestemd op uw specifieke klachten." },
          { type: "h3", text: "Uitleg en advies" },
          { type: "p", text: "Inzicht in uw klachten is een belangrijk onderdeel van de behandeling. U krijgt uitleg over mogelijke oorzaken van uw hoofdpijn, factoren die de klachten be\u00efnvloeden en manieren om overbelasting te voorkomen." },
          { type: "h3", text: "Oefentherapie" },
          { type: "p", text: "Specifieke oefeningen kunnen helpen om nek-, kaak- en schouderspieren te ontspannen, spierkracht en stabiliteit te verbeteren en de beweeglijkheid van de nek te vergroten. Deze oefeningen helpen om de belasting van het hoofd-halsgebied beter te verdelen." },
          { type: "h3", text: "Behandeling van spieren en gewrichten" },
          { type: "p", text: "De fysiotherapeut kan verschillende technieken gebruiken om pijn en spanning te verminderen, zoals manuele technieken voor de nek, behandeling van triggerpoints in spieren en ontspanning van de kauwspieren." },
          { type: "h3", text: "Kaaktraining" },
          { type: "p", text: "Wanneer hoofdpijn samenhangt met kaakspanning of klemgedrag, kunnen specifieke oefeningen en adviezen voor de kaak helpen om de belasting te verminderen." },
          { type: "h3", text: "Houdingsadvies" },
          { type: "p", text: "Omdat houding een belangrijke rol kan spelen bij hoofdpijn, kan er aandacht zijn voor werkhouding, schermgebruik en de positie van hoofd en nek." },
        ],
      },
    ],
    faq: [
      { q: "Kan fysiotherapie helpen bij hoofdpijn?", a: "Ja, vooral wanneer de hoofdpijn samenhangt met nekklachten, spierspanning of kaakproblemen. In deze gevallen kan fysiotherapie helpen om de klachten te verminderen." },
      { q: "Is spanningshoofdpijn gevaarlijk?", a: "Spanningshoofdpijn is meestal niet gevaarlijk, maar kan wel erg hinderlijk zijn. Behandeling kan helpen om de frequentie en intensiteit van de klachten te verminderen." },
      { q: "Heeft stress invloed op hoofdpijn?", a: "Ja. Stress kan leiden tot verhoogde spierspanning in het hoofd-halsgebied en daardoor hoofdpijn veroorzaken of verergeren." },
      { q: "Hoe lang duurt herstel van hoofdpijnklachten?", a: "Dit verschilt per persoon. Sommige mensen merken al binnen enkele behandelingen verbetering, terwijl andere klachten meer tijd nodig hebben." },
      { q: "Kan mijn kaak hoofdpijn veroorzaken?", a: "Ja. Overbelasting van de kauwspieren, tandenknarsen of klemmen kan leiden tot hoofdpijn, vooral rond de slapen." },
    ],
    closing: {
      title: "Blijft u last houden van hoofdpijn?",
      paragraphs: [
        "Terugkerende hoofdpijn kan een grote invloed hebben op uw dagelijks leven. Gelukkig zijn veel vormen van hoofdpijn goed te behandelen wanneer de onderliggende oorzaak wordt aangepakt.",
        "Blijft u last houden van hoofdpijn, nekklachten of spanning in de kaak? Neem gerust contact op voor advies of het maken van een afspraak. Samen kijken we naar de oorzaak van uw klachten en naar een behandeling die past bij uw situatie.",
      ],
    },
  },
  {
    slug: "duizeligheid-vestibulaire-revalidatie",
    name: "Duizeligheid",
    shortName: "Duizeligheid",
    category: "klacht",
    seoTitle: "Duizeligheid behandelen – BPPD en vestibulaire therapie",
    metaDescription:
      "Last van duizeligheid of draaiduizeligheid? Lees over BPPD, PPPD en vestibulaire revalidatie en hoe een gespecialiseerde fysiotherapeut kan helpen.",
    lead: "Heeft u last van duizeligheid of een draaierig gevoel?",
    card: "Draaiduizeligheid (BPPD), instabiliteit of een zweverig gevoel — behandelbaar met vestibulaire revalidatie.",
    sections: [
      {
        id: "introductie",
        title: "Heeft u last van duizeligheid of een draaierig gevoel?",
        blocks: [
          { type: "p", text: "Veel mensen ervaren weleens duizeligheid. Soms voelt het alsof de wereld om u heen draait, terwijl het op andere momenten meer een gevoel van instabiliteit of lichtheid in het hoofd is. Voor sommigen ontstaat de klacht plotseling bij het draaien in bed, terwijl anderen langdurig een onzeker of zweverig gevoel ervaren." },
          { type: "p", text: "Duizeligheid kan erg vervelend zijn en invloed hebben op dagelijkse activiteiten zoals lopen, autorijden, werken of sporten. In veel gevallen ligt de oorzaak in het evenwichtsorgaan." },
          { type: "p", text: "Een gespecialiseerde fysiotherapeut kan helpen bij het onderzoeken van deze klachten en het begeleiden van het herstel. Met gerichte behandeling en oefeningen kunnen veel mensen hun balans en vertrouwen weer terugkrijgen." },
        ],
      },
      {
        id: "wat-is-duizeligheid",
        title: "Wat zijn duizeligheidsklachten?",
        blocks: [
          { type: "p", text: "Duizeligheid is een verzamelnaam voor verschillende sensaties waarbij het evenwicht verstoord voelt. Het kan gaan om:" },
          { type: "list", items: ["het gevoel dat de omgeving draait", "het gevoel dat u zelf draait", "een licht gevoel in het hoofd", "een gevoel van instabiliteit of wankel lopen"] },
          { type: "p", text: "Het evenwicht in het lichaam wordt geregeld door een samenwerking tussen het evenwichtsorgaan in het binnenoor, de ogen, het gevoel uit spieren en gewrichten en de hersenen. Wanneer \u00e9\u00e9n van deze systemen verstoord raakt, kan duizeligheid ontstaan." },
          { type: "p", text: "Een veelvoorkomende oorzaak is een probleem in het vestibulaire systeem (het evenwichtsorgaan). Binnen deze groep komen verschillende aandoeningen voor, zoals:" },
          { type: "list", items: [
            "BPPD (Benigne Paroxysmale Positieduizeligheid)",
            "Vestibulaire hypofunctie (verminderde werking van het evenwichtsorgaan)",
            "PPPD (Persistente Posturale Perceptuele Duizeligheid)",
            "Ziekte van M\u00e9ni\u00e8re",
            "Vestibulaire migraine",
          ] },
          { type: "p", text: "Hoewel deze aandoeningen verschillend zijn, kunnen ze vaak goed behandeld worden met gerichte fysiotherapie." },
        ],
      },
      {
        id: "symptomen",
        title: "Symptomen van duizeligheid",
        blocks: [
          { type: "p", text: "Duizeligheidsklachten kunnen zich op verschillende manieren uiten. De ervaring verschilt sterk per persoon." },
          { type: "h3", text: "Draaiduizeligheid" },
          { type: "p", text: "Bij sommige mensen voelt het alsof de wereld om hen heen draait. Dit wordt ook wel vertigo genoemd. Dit kan bijvoorbeeld optreden bij:" },
          { type: "list", items: ["omdraaien in bed", "omhoog kijken", "bukken", "snel bewegen van het hoofd"] },
          { type: "p", text: "Dit type duizeligheid komt vaak voor bij BPPD." },
          { type: "h3", text: "Onzeker of wankel gevoel" },
          { type: "p", text: "Andere mensen ervaren meer een gevoel van instabiliteit of onzeker lopen. Het kan voelen alsof u uit balans bent of alsof de grond beweegt. Dit kan bijvoorbeeld optreden tijdens lopen, bewegen in drukke omgevingen of kijken naar bewegende beelden." },
          { type: "h3", text: "Licht gevoel in het hoofd" },
          { type: "p", text: "Sommige mensen beschrijven hun klachten als een licht of zweverig gevoel. Dit kan samengaan met vermoeidheid, concentratieproblemen of spanning." },
          { type: "h3", text: "Andere mogelijke klachten" },
          { type: "list", items: ["misselijkheid", "wazig zien", "moeite met focussen", "onzekerheid bij bewegen", "spanning in nek of schouders", "vermoeidheid"] },
          { type: "p", text: "Omdat duizeligheid verschillende oorzaken kan hebben, is een goede beoordeling belangrijk." },
        ],
      },
      {
        id: "oorzaken",
        title: "Mogelijke oorzaken van duizeligheid",
        blocks: [
          { type: "p", text: "Er zijn verschillende oorzaken voor duizeligheid. In veel gevallen ligt de oorzaak in het evenwichtsorgaan." },
          { type: "h3", text: "BPPD (Benigne Paroxysmale Positieduizeligheid)" },
          { type: "p", text: "BPPD is \u00e9\u00e9n van de meest voorkomende oorzaken van draaiduizeligheid. Hierbij verplaatsen kleine kalkkristallen zich in het evenwichtsorgaan. Dit kan leiden tot korte maar heftige duizeligheidsaanvallen, bijvoorbeeld bij het omdraaien in bed, gaan liggen of opstaan, of naar boven kijken. Hoewel de klachten heftig kunnen zijn, is BPPD vaak goed te behandelen." },
          { type: "h3", text: "Verminderde werking van het evenwichtsorgaan" },
          { type: "p", text: "Soms werkt \u00e9\u00e9n van de evenwichtsorganen minder goed. Dit kan ontstaan na bijvoorbeeld een virusinfectie, een ontsteking van het evenwichtsorgaan of een periode van ziekte. Hierdoor kan een langdurig gevoel van instabiliteit ontstaan." },
          { type: "h3", text: "PPPD (Persistente Posturale Perceptuele Duizeligheid)" },
          { type: "p", text: "Bij PPPD blijft het duizelige gevoel langer aanwezig, vaak na een eerdere vestibulaire aandoening. Mensen ervaren bijvoorbeeld een zweverig of instabiel gevoel, verergering van klachten in drukke omgevingen en klachten bij visuele prikkels (bijvoorbeeld in een supermarkt). Stress, spanning en vermijdingsgedrag kunnen hierbij een rol spelen." },
          { type: "h3", text: "Nekklachten" },
          { type: "p", text: "Soms kan duizeligheid ook samenhangen met spanning of problemen in de nek. Dit wordt ook wel cervicogene duizeligheid genoemd." },
          { type: "h3", text: "Andere oorzaken" },
          { type: "p", text: "Duizeligheid kan ook ontstaan door andere factoren, zoals stress of overbelasting, vermoeidheid, lage bloeddruk of bepaalde medicatie. Daarom is het belangrijk om de oorzaak zorgvuldig te onderzoeken." },
        ],
      },
      {
        id: "wanneer-hulp",
        title: "Wanneer is het verstandig om hulp te zoeken?",
        blocks: [
          { type: "p", text: "Duizeligheid kan tijdelijk zijn en vanzelf verdwijnen. Toch kan het verstandig zijn om hulp te zoeken wanneer de klachten aanhouden. Het is raadzaam om een specialist te raadplegen wanneer:" },
          { type: "list", items: [
            "de duizeligheid langer dan enkele weken duurt",
            "u regelmatig aanvallen van draaiduizeligheid heeft",
            "u zich onzeker voelt tijdens lopen of bewegen",
            "de klachten invloed hebben op werk of dagelijkse activiteiten",
            "u situaties gaat vermijden uit angst voor duizeligheid",
          ] },
          { type: "p", text: "Een goede beoordeling kan helpen om duidelijkheid te krijgen over de oorzaak en de juiste behandeling te starten." },
        ],
      },
      {
        id: "hoe-helpt",
        title: "Hoe kan een gespecialiseerde fysiotherapeut helpen?",
        blocks: [
          { type: "p", text: "Een fysiotherapeut met ervaring in duizeligheidsklachten en vestibulaire revalidatie kan helpen bij het onderzoeken en behandelen van evenwichtsproblemen. Tijdens het eerste consult wordt uitgebreid gekeken naar:" },
          { type: "list", items: ["de aard van uw duizeligheid", "wanneer de klachten optreden", "hoe lang de klachten al bestaan", "mogelijke uitlokkende factoren"] },
          { type: "p", text: "Daarnaast wordt lichamelijk onderzoek gedaan, zoals:" },
          { type: "list", items: ["testen van het evenwichtsorgaan", "beoordelen van oogbewegingen", "onderzoeken van balans en stabiliteit", "beoordeling van nek en houding"] },
          { type: "p", text: "Met deze informatie kan worden vastgesteld welke vorm van duizeligheid waarschijnlijk speelt." },
        ],
      },
      {
        id: "behandeling",
        title: "Behandeling van duizeligheid in de praktijk",
        blocks: [
          { type: "p", text: "De behandeling wordt altijd afgestemd op de oorzaak van de klachten. Vaak bestaat deze uit een combinatie van verschillende behandelmethoden." },
          { type: "h3", text: "Repositiemanoeuvres bij BPPD" },
          { type: "p", text: "Bij BPPD kunnen specifieke behandelingen worden uitgevoerd waarbij de kalkkristallen in het evenwichtsorgaan weer naar de juiste plek worden geleid. Deze manoeuvres kunnen de klachten vaak snel verminderen." },
          { type: "h3", text: "Vestibulaire revalidatie" },
          { type: "p", text: "Vestibulaire revalidatie bestaat uit specifieke oefeningen voor het evenwichtssysteem. Deze oefeningen helpen om het evenwichtssysteem te trainen, het lichaam te laten wennen aan beweging, balans en stabiliteit te verbeteren en duizeligheid geleidelijk te verminderen." },
          { type: "h3", text: "Oefeningen voor ogen en hoofdbeweging" },
          { type: "p", text: "Het evenwichtssysteem werkt nauw samen met de ogen. Daarom kunnen oefeningen gericht zijn op stabiliteit van het zicht, co\u00f6rdinatie tussen ogen en hoofd en het verbeteren van focus tijdens beweging." },
          { type: "h3", text: "Balans- en bewegingsherstel" },
          { type: "p", text: "Bij langdurige duizeligheid kunnen mensen onzeker worden in hun bewegingen. Oefeningen kunnen helpen om vertrouwen in bewegen terug te krijgen, balans te verbeteren en dagelijkse activiteiten weer op te bouwen." },
          { type: "h3", text: "Uitleg en begeleiding" },
          { type: "p", text: "Goede uitleg over de klacht helpt veel mensen om hun klachten beter te begrijpen en minder angst voor duizeligheid te ervaren. Dit is vooral belangrijk bij langdurige klachten zoals PPPD." },
        ],
      },
    ],
    faq: [
      { q: "Kan duizeligheid vanzelf overgaan?", a: "Ja, sommige vormen van duizeligheid verdwijnen vanzelf. Wanneer klachten langer aanhouden of regelmatig terugkomen, kan behandeling het herstel versnellen." },
      { q: "Is BPPD gevaarlijk?", a: "BPPD kan vervelend zijn, maar is niet gevaarlijk. De klachten kunnen vaak goed behandeld worden met specifieke manoeuvres." },
      { q: "Helpen oefeningen bij duizeligheid?", a: "Ja. Vestibulaire oefeningen kunnen het evenwichtssysteem trainen en helpen om het lichaam beter met beweging om te laten gaan." },
      { q: "Hoe lang duurt herstel van duizeligheid?", a: "Dit verschilt per persoon en per oorzaak. Sommige mensen herstellen binnen enkele dagen of weken, terwijl andere klachten meer tijd nodig hebben." },
      { q: "Moet ik rust nemen bij duizeligheid?", a: "Volledige rust is meestal niet nodig en kan herstel soms juist vertragen. Geleidelijke beweging en training van het evenwicht kunnen juist helpen bij herstel." },
    ],
    closing: {
      title: "Blijft u last houden van duizeligheid?",
      paragraphs: [
        "Duizeligheid kan veel invloed hebben op het dagelijks leven. Gelukkig zijn veel vormen van duizeligheid goed te behandelen met gerichte fysiotherapie.",
        "Blijft u last houden van draaiduizeligheid, instabiliteit of onzekerheid bij bewegen? Neem gerust contact op voor advies of het maken van een afspraak. Samen kijken we naar de oorzaak van uw klachten en naar een behandeling die past bij uw situatie.",
      ],
    },
  },
  {
    slug: "aangezichtspijn-behandeling",
    name: "Aangezichtspijn",
    shortName: "Aangezichtspijn",
    category: "klacht",
    seoTitle: "Aangezichtspijn behandelen | Orofaciale fysiotherapie",
    metaDescription:
      "Last van pijn in het gezicht of kaak? Lees oorzaken, symptomen en hoe orofaciale fysiotherapie helpt bij aangezichtspijn.",
    lead: "Pijn in het gezicht kan erg vervelend en verwarrend zijn.",
    card: "Zeurende, drukkende of stekende pijn in het gezicht, de kaak of rond het oog — met of zonder duidelijke oorzaak.",
    sections: [
      {
        id: "introductie",
        title: "Pijn in het gezicht?",
        blocks: [
          { type: "p", text: "Pijn in het gezicht kan erg vervelend en verwarrend zijn. Het kan gaan om een zeurende pijn in de kaak, een stekende pijn in de wang of een drukkend gevoel rond het oog of de slaap. Soms is de oorzaak duidelijk, maar vaak ook niet." },
          { type: "p", text: "Veel mensen met aangezichtspijn lopen langere tijd rond met klachten zonder dat ze precies weten waar het vandaan komt. Dit kan onzekerheid geven. Een gespecialiseerde orofaciaal fysiotherapeut kan helpen om de oorzaak te achterhalen en de klachten te verminderen." },
        ],
      },
      {
        id: "wat-is-aangezichtspijn",
        title: "Wat is aangezichtspijn?",
        blocks: [
          { type: "p", text: "Aangezichtspijn is een verzamelnaam voor pijnklachten in het gezicht, de kaak of rondom de mond. De pijn kan afkomstig zijn van verschillende structuren, zoals:" },
          { type: "list", items: ["spieren (bijvoorbeeld kauwspieren)", "gewrichten (zoals het kaakgewricht)", "zenuwen", "soms vanuit de nek of houding"] },
          { type: "p", text: "Er zijn verschillende vormen van aangezichtspijn. Denk aan:" },
          { type: "list", items: [
            "spiergerelateerde pijn (bijvoorbeeld door spanning of overbelasting)",
            "kaakklachten (TMD)",
            "zenuwpijn (zoals trigeminusneuralgie)",
            "chronische aangezichtspijn zonder duidelijke oorzaak",
          ] },
          { type: "p", text: "Het is belangrijk om goed te onderzoeken waar uw klachten vandaan komen, omdat de behandeling per oorzaak verschilt." },
        ],
      },
      {
        id: "symptomen",
        title: "Symptomen van aangezichtspijn",
        blocks: [
          { type: "p", text: "De klachten kunnen sterk vari\u00ebren. Veelvoorkomende symptomen zijn:" },
          { type: "h3", text: "Pijn in het gezicht" },
          { type: "list", items: ["zeurende, drukkende of stekende pijn", "pijn in wang, kaak, slaap of rond het oog", "pijn aan \u00e9\u00e9n of beide kanten van het gezicht"] },
          { type: "h3", text: "Kaakklachten" },
          { type: "list", items: ["pijn bij kauwen of praten", "knappen of kraken van de kaak", "moeite met het openen van de mond"] },
          { type: "h3", text: "Spierklachten" },
          { type: "list", items: ["spanning in kaak of gezicht", "vermoeid gevoel in de kaken", "klemmen of tandenknarsen"] },
          { type: "h3", text: "Zenuwgerelateerde klachten" },
          { type: "list", items: ["schietende, elektrische pijnscheuten", "overgevoeligheid bij aanraking", "tintelingen of doof gevoel"] },
          { type: "h3", text: "Andere klachten" },
          { type: "list", items: ["hoofdpijn", "nekklachten", "oorpijn zonder oorprobleem"] },
          { type: "p", text: "De klachten kunnen continu aanwezig zijn of juist in aanvallen optreden." },
        ],
      },
      {
        id: "oorzaken",
        title: "Mogelijke oorzaken",
        blocks: [
          { type: "p", text: "Aangezichtspijn kan verschillende oorzaken hebben. Vaak is het een combinatie van factoren." },
          { type: "h3", text: "Spierspanning" },
          { type: "list", items: ["klemmen of knarsen van de tanden", "stress en spanning", "overbelasting van de kauwspieren"] },
          { type: "h3", text: "Kaakgewrichtsproblemen" },
          { type: "list", items: ["verkeerde stand of beweging van de kaak", "overbelasting van het kaakgewricht", "discusproblemen"] },
          { type: "h3", text: "Zenuwprikkeling" },
          { type: "p", text: "Bij sommige vormen van aangezichtspijn speelt prikkeling of overgevoeligheid van zenuwen een rol, zoals bij trigeminusneuralgie. Ook bij chronische pijn kan het zenuwstelsel gevoeliger raken, waardoor pijn blijft bestaan zonder duidelijke weefselschade." },
        ],
      },
      {
        id: "hoe-helpt",
        title: "Hoe kan een orofaciaal fysiotherapeut helpen?",
        blocks: [
          { type: "p", text: "Een orofaciaal fysiotherapeut is gespecialiseerd in klachten van het hoofd-halsgebied, waaronder aangezichtspijn." },
          { type: "h3", text: "Uitgebreid onderzoek" },
          { type: "p", text: "Tijdens het eerste consult wordt gekeken naar:" },
          { type: "list", items: ["uw klachten en het verloop", "spanning en functie van kauwspieren", "beweging van het kaakgewricht", "nek en houding", "mogelijke invloed van stress"] },
          { type: "h3", text: "Duidelijke uitleg" },
          { type: "p", text: "U krijgt uitleg over de mogelijke oorzaak van uw klachten, hoe pijn ontstaat en in stand blijft, en wat u zelf kunt doen. Dit helpt om meer grip te krijgen op uw situatie." },
        ],
      },
      {
        id: "behandeling",
        title: "Behandeling van aangezichtspijn in de praktijk",
        blocks: [
          { type: "p", text: "De behandeling wordt afgestemd op uw klachten en is gericht op het verminderen van pijn en het herstellen van normale functie." },
          { type: "h3", text: "Oefentherapie" },
          { type: "list", items: ["oefeningen voor kaakcontrole", "ontspanning van de kauwspieren", "verbeteren van bewegingspatronen"] },
          { type: "h3", text: "Kaaktraining" },
          { type: "list", items: ["aanleren van een ontspannen kaakhouding", "verminderen van klemmen en knarsen", "bewustwording van gewoontes"] },
          { type: "h3", text: "Manuele technieken" },
          { type: "list", items: ["behandeling van het kaakgewricht", "mobilisaties van nek en bovenrug", "verminderen van spierspanning"] },
          { type: "h3", text: "Houdingsadvies" },
          { type: "list", items: ["verbeteren van werkhouding", "verminderen van belasting op nek en kaak", "praktische tips voor het dagelijks leven"] },
          { type: "h3", text: "Ontspanning en stressregulatie" },
          { type: "list", items: ["inzicht in de invloed van stress", "oefeningen voor ontspanning", "doorbreken van spanningspatronen"] },
          { type: "p", text: "Het doel is niet alleen klachten verminderen, maar ook voorkomen dat ze terugkomen." },
        ],
      },
    ],
    faq: [
      { q: "Is aangezichtspijn gevaarlijk?", a: "Meestal niet. In de meeste gevallen is er geen ernstige aandoening, maar het is wel belangrijk om de oorzaak goed te laten onderzoeken." },
      { q: "Gaat het vanzelf over?", a: "Soms wel, maar klachten kunnen ook blijven bestaan of verergeren zonder behandeling." },
      { q: "Kan stress echt pijn in mijn gezicht veroorzaken?", a: "Ja, stress kan leiden tot spierspanning en klemgedrag, wat aangezichtspijn kan veroorzaken of verergeren." },
      { q: "Helpt fysiotherapie bij kaakklachten?", a: "Ja, vooral bij spier- en gewrichtsgerelateerde klachten is fysiotherapie vaak effectief." },
      { q: "Moet ik stoppen met kauwgom kauwen?", a: "Vaak wel, in ieder geval tijdelijk. Overbelasting van de kaak kan klachten in stand houden." },
    ],
    closing: {
      title: "Heeft u last van aangezichtspijn?",
      paragraphs: [
        "Aangezichtspijn kan een grote invloed hebben op uw dagelijks leven. Eten, praten en zelfs ontspannen kunnen moeilijker worden door de pijn en spanning. Met de juiste begeleiding is er vaak veel mogelijk.",
        "Heeft u last van aangezichtspijn of twijfelt u over uw klachten? Neem gerust contact op voor advies of het maken van een afspraak. We helpen u graag verder.",
      ],
    },
  },
  {
    slug: "ziekte-van-bell-aangezichtsverlamming-behandeling",
    name: "Aangezichtsverlamming (Ziekte van Bell)",
    shortName: "Aangezichtsverlamming",
    category: "klacht",
    seoTitle: "Ziekte van Bell behandelen | Kaakfysiotherapie",
    metaDescription:
      "Last van een aangezichtsverlamming (Bell)? Ontdek hoe orofaciale fysiotherapie en mime therapie helpen bij herstel en controle.",
    lead: "Wordt uw gezicht plotseling scheef of voelt het slap aan?",
    card: "Perifere aangezichtsverlamming (IPAV): begeleiding bij herstel van mimiek en spiercontrole, o.a. met mime therapie.",
    sections: [
      {
        id: "introductie",
        title: "Wordt uw gezicht plotseling scheef?",
        blocks: [
          { type: "p", text: "Wordt uw gezicht plotseling scheef, kunt u \u00e9\u00e9n oog niet goed sluiten of voelt uw gezicht slap aan? Dan kan er sprake zijn van de Ziekte van Bell, ook wel een perifere aangezichtsverlamming genoemd. Dit kan schrikken zijn en invloed hebben op spreken, eten en uw gezichtsuitdrukking." },
          { type: "p", text: "Veel mensen zoeken hulp omdat ze merken dat hun herstel niet vanzelf gaat of omdat ze restklachten houden. Een orofaciaal fysiotherapeut (gespecialiseerd in het hoofd-halsgebied) kan u begeleiden bij het herstel en helpen om de controle over uw gezichtsspieren terug te krijgen." },
        ],
      },
      {
        id: "wat-is-bell",
        title: "Wat is de Ziekte van Bell (perifere aangezichtsverlamming)?",
        blocks: [
          { type: "p", text: "De Ziekte van Bell is een plotseling optredende verlamming van de spieren aan \u00e9\u00e9n kant van het gezicht. Deze wordt veroorzaakt door een probleem met de aangezichtszenuw (nervus facialis), die de spieren in het gezicht aanstuurt." },
          { type: "p", text: "Bij een perifere aangezichtsverlamming werkt deze zenuw tijdelijk minder goed of helemaal niet. Daardoor kunnen de spieren niet goed bewegen. Dit leidt tot een scheef gezicht of verminderde controle over mimiek." },
          { type: "p", text: "In de meeste gevallen herstelt de zenuw gedeeltelijk of volledig, maar dit proces kan weken tot maanden duren. Soms blijven er klachten bestaan, zoals spierspanning of ongewenste bewegingen." },
        ],
      },
      {
        id: "symptomen",
        title: "Symptomen van de Ziekte van Bell",
        blocks: [
          { type: "p", text: "De klachten ontstaan meestal plotseling en zijn vaak aan \u00e9\u00e9n kant van het gezicht aanwezig." },
          { type: "h3", text: "Veelvoorkomende symptomen" },
          { type: "list", items: [
            "scheefstand van het gezicht",
            "mondhoek hangt naar beneden",
            "moeite met praten of duidelijk articuleren",
            "niet goed kunnen sluiten van het oog",
            "verminderd knipperen",
            "kwijlen of moeite met drinken",
            "verlies van mimiek (bijvoorbeeld niet kunnen lachen of fronsen)",
          ] },
          { type: "h3", text: "Andere mogelijke klachten" },
          { type: "list", items: [
            "gevoel van spanning of stijfheid in het gezicht",
            "overgevoeligheid voor geluid",
            "veranderde smaak",
            "tranen of juist een droog oog",
            "vermoeidheid van de gezichtsspieren",
          ] },
          { type: "p", text: "In een later stadium kunnen ook zogenaamde synkinesie\u00ebn ontstaan: onbedoelde meebewegingen, zoals een oog dat sluit tijdens lachen." },
        ],
      },
      {
        id: "oorzaken",
        title: "Mogelijke oorzaken",
        blocks: [
          { type: "p", text: "De exacte oorzaak van de Ziekte van Bell is niet altijd duidelijk, maar er wordt vaak gedacht aan een ontsteking van de aangezichtszenuw. Factoren die een rol kunnen spelen:" },
          { type: "list", items: [
            "virusinfecties (zoals herpes simplex)",
            "verminderde weerstand",
            "stress of overbelasting",
            "kou of tocht",
            "hormonale veranderingen",
          ] },
          { type: "p", text: "Door de ontsteking zwelt de zenuw op in een smalle doorgang in de schedel, waardoor de functie tijdelijk verstoord raakt." },
        ],
      },
      {
        id: "wanneer-hulp",
        title: "Wanneer is het verstandig om hulp te zoeken?",
        blocks: [
          { type: "p", text: "Bij een plotselinge aangezichtsverlamming is het belangrijk om altijd eerst contact op te nemen met de huisarts. Deze beoordeelt of er sprake is van de Ziekte van Bell of een andere oorzaak." },
          { type: "p", text: "Neem contact op met een fysiotherapeut wanneer:" },
          { type: "list", items: [
            "het herstel uitblijft na enkele weken",
            "u moeite houdt met spreken, eten of mimiek",
            "er restklachten ontstaan zoals stijfheid of pijn",
            "u ongewenste bewegingen (synkinesie\u00ebn) ontwikkelt",
            "u onzeker bent over hoe u uw gezichtsspieren moet gebruiken",
          ] },
          { type: "p", text: "Vroege begeleiding kan helpen om het herstel te optimaliseren en verkeerde bewegingspatronen te voorkomen." },
        ],
      },
      {
        id: "hoe-helpt",
        title: "Hoe kan een orofaciaal fysiotherapeut helpen?",
        blocks: [
          { type: "p", text: "Een orofaciaal fysiotherapeut is gespecialiseerd in klachten van het gezicht, de kaak en de nek. Bij een aangezichtsverlamming richt de behandeling zich op het herstellen van spiercontrole en het voorkomen van complicaties." },
          { type: "p", text: "Tijdens het eerste consult wordt onder andere gekeken naar de beweeglijkheid van uw gezichtsspieren, de mate van herstel, eventuele meebewegingen en de invloed van de klachten op uw dagelijks leven. Op basis hiervan wordt een persoonlijk behandelplan opgesteld." },
        ],
      },
      {
        id: "behandeling",
        title: "Behandeling in de praktijk: mime therapie",
        blocks: [
          { type: "p", text: "Bij een perifere aangezichtsverlamming wordt gewerkt met mime therapie: een specifieke behandelmethode gericht op het herstellen van de controle over de gezichtsspieren en het verbeteren van de symmetrie van het gezicht." },
          { type: "h3", text: "Onderdelen van de behandeling" },
          { type: "list", items: [
            "uitleg over het herstelproces en wat u kunt verwachten",
            "massage- en ontspanningstechnieken voor de gezichtsspieren",
            "gerichte oefeningen voor mimiek en spiercontrole",
            "aanleren van bewust en ontspannen bewegen van het gezicht",
            "voorkomen en verminderen van synkinesie\u00ebn (meebewegingen)",
            "adviezen voor oogverzorging, eten en spreken",
          ] },
          { type: "p", text: "De behandeling wordt afgestemd op de fase van herstel. Rustig en gedoseerd oefenen is hierbij belangrijk: te intensief trainen kan het herstel juist verstoren." },
        ],
      },
    ],
    faq: [
      { q: "Herstelt een aangezichtsverlamming volledig?", a: "In de meeste gevallen herstelt de zenuw gedeeltelijk of volledig. Dit proces kan weken tot maanden duren. Soms blijven restklachten bestaan; gerichte begeleiding kan dan helpen." },
      { q: "Wat is mime therapie?", a: "Mime therapie is een specifieke behandelmethode bij aangezichtsverlamming, gericht op het herstellen van de controle over de gezichtsspieren, het verbeteren van symmetrie en het voorkomen van ongewenste meebewegingen." },
      { q: "Kan ik zelf oefenen met mijn gezicht?", a: "Oefenen is belangrijk, maar de juiste dosering en techniek zijn essentieel. Te intensief of verkeerd oefenen kan het herstel verstoren. Laat u hierbij begeleiden." },
      { q: "Wat zijn synkinesieën?", a: "Synkinesieën zijn onbedoelde meebewegingen die kunnen ontstaan tijdens het herstel, zoals een oog dat sluit tijdens lachen. Met gerichte therapie kunnen deze verminderd of voorkomen worden." },
      { q: "Wanneer moet ik naar de huisarts?", a: "Bij een plotselinge aangezichtsverlamming altijd direct. De huisarts beoordeelt of er sprake is van de Ziekte van Bell of een andere oorzaak." },
    ],
    closing: {
      title: "Begeleiding bij herstel van uw aangezichtsverlamming",
      paragraphs: [
        "Een aangezichtsverlamming heeft veel impact: op uw uiterlijk, uw spreken en uw zelfvertrouwen. Met de juiste begeleiding kunt u stap voor stap werken aan herstel van controle over uw gezichtsspieren.",
        "Heeft u een aangezichtsverlamming (gehad) en houdt u klachten? Neem gerust contact op voor advies of het maken van een afspraak. We denken graag met u mee.",
      ],
    },
  },
  {
    slug: "tinnitus-behandeling-kaakfysiotherapie",
    name: "Tinnitus (oorsuizen)",
    shortName: "Tinnitus & oorpijn",
    category: "klacht",
    seoTitle: "Tinnitus behandeling | Kaakfysiotherapie helpt",
    metaDescription:
      "Last van oorsuizen (tinnitus)? Ontdek hoe orofaciale fysiotherapie kan helpen bij klachten in kaak, nek en hoofd.",
    lead: "Ervaart u een piep, ruis of brom in uw oor die maar niet weggaat?",
    card: "Oorsuizen met een somatosensorische component: tinnitus die beïnvloed wordt door kaak, nek of spierspanning.",
    sections: [
      {
        id: "introductie",
        title: "Een piep, ruis of brom die maar niet weggaat?",
        blocks: [
          { type: "p", text: "Ervaart u een piep, ruis of brom in uw oor die maar niet weggaat? Dan kan er sprake zijn van tinnitus, ook wel oorsuizen genoemd. Voor veel mensen is dit een vervelende en soms zelfs belastende klacht. Het kan uw concentratie, slaap en dagelijks functioneren be\u00efnvloeden." },
          { type: "p", text: "Wat minder bekend is: klachten van tinnitus kunnen samenhangen met spanningen of problemen in de kaak, nek of houding. In die gevallen kan een orofaciaal fysiotherapeut (gespecialiseerd in het hoofd-halsgebied) u helpen om grip te krijgen op uw klachten." },
        ],
      },
      {
        id: "wat-is-tinnitus",
        title: "Wat is tinnitus?",
        blocks: [
          { type: "p", text: "Tinnitus betekent dat u geluid hoort zonder dat er een externe geluidsbron is. Dit geluid kan continu aanwezig zijn of af en toe optreden." },
          { type: "p", text: "Het is geen ziekte op zichzelf, maar een symptoom. De beleving verschilt sterk per persoon. Waar de \u00e9\u00e9n er weinig last van heeft, kan het voor een ander veel impact hebben op het dagelijks leven." },
          { type: "p", text: "Tinnitus kan ontstaan door veranderingen in het gehoor, maar ook door factoren buiten het oor, zoals spierspanning of gewrichtsproblemen in het hoofd-halsgebied." },
        ],
      },
      {
        id: "symptomen",
        title: "Symptomen van tinnitus",
        blocks: [
          { type: "p", text: "Tinnitus kan zich op verschillende manieren uiten. Veelvoorkomende klachten zijn:" },
          { type: "list", items: [
            "een piep, fluittoon of suis in \u00e9\u00e9n of beide oren",
            "een brommend, zoemend of kloppend geluid",
            "geluid dat constant aanwezig is of juist wisselt in intensiteit",
            "verergering van het geluid bij stress of vermoeidheid",
            "moeite met concentreren",
            "slaapproblemen",
            "gevoeligheid voor geluid (hyperacusis)",
          ] },
          { type: "p", text: "Sommige mensen merken dat de tinnitus verandert bij bewegingen van de kaak, nek of schouders. Dit kan een belangrijke aanwijzing zijn dat het bewegingsapparaat een rol speelt." },
        ],
      },
      {
        id: "oorzaken",
        title: "Mogelijke oorzaken",
        blocks: [
          { type: "p", text: "Tinnitus kan verschillende oorzaken hebben. Soms is er \u00e9\u00e9n duidelijke oorzaak, maar vaak spelen meerdere factoren tegelijk een rol. Veelvoorkomende oorzaken:" },
          { type: "list", items: [
            "gehoorschade (bijvoorbeeld door harde geluiden)",
            "oorproblemen (zoals een oorontsteking of oorsmeerprop)",
            "stress en spanning",
            "vermoeidheid of overbelasting",
          ] },
          { type: "h3", text: "Invloed van kaak en nek" },
          { type: "p", text: "Bij een deel van de mensen hangt tinnitus samen met het bewegingsapparaat, zoals:" },
          { type: "list", items: [
            "spanning in de kauwspieren",
            "kaakproblemen (zoals knarsen of klemmen)",
            "nekklachten of een stijve nek",
            "een belastende houding (bijvoorbeeld langdurig beeldschermwerk)",
          ] },
          { type: "p", text: "Dit noemen we ook wel somatosensorische tinnitus. Hierbij kan de tinnitus be\u00efnvloed worden door beweging of spanning in spieren en gewrichten." },
        ],
      },
      {
        id: "wanneer-hulp",
        title: "Wanneer is het verstandig om hulp te zoeken?",
        blocks: [
          { type: "p", text: "Het is aan te raden om hulp te zoeken wanneer:" },
          { type: "list", items: [
            "de tinnitus langer dan enkele weken aanhoudt",
            "u er dagelijks last van heeft",
            "uw slaap of concentratie verstoord is",
            "de klachten toenemen",
            "u ook klachten heeft van de kaak, nek of schouders",
            "u merkt dat stress invloed heeft op uw tinnitus",
          ] },
          { type: "p", text: "Een goede eerste stap is vaak een bezoek aan de huisarts, audicien of KNO-arts om oorzaken in het oor uit te sluiten. Daarna kan een orofaciaal fysiotherapeut beoordelen of uw klachten be\u00efnvloedbaar zijn via het bewegingsapparaat." },
        ],
      },
      {
        id: "hoe-helpt",
        title: "Hoe kan een orofaciaal fysiotherapeut helpen?",
        blocks: [
          { type: "p", text: "Een orofaciaal fysiotherapeut is gespecialiseerd in klachten van het hoofd, de kaak en de nek. Bij tinnitus wordt gekeken of er een relatie is tussen uw klachten en het houdings- en bewegingsapparaat." },
          { type: "p", text: "Tijdens de intake wordt uitgebreid gekeken naar:" },
          { type: "list", items: [
            "uw klachten en wanneer deze optreden",
            "invloed van stress en belasting",
            "kaakfunctie (bijvoorbeeld klemmen of knarsen)",
            "spierspanning in kaak, nek en schouders",
            "houding en bewegingspatronen",
          ] },
          { type: "p", text: "Ook wordt onderzocht of uw tinnitus verandert bij bewegingen of druk op bepaalde spieren. Dit geeft belangrijke informatie over de mogelijke oorzaak." },
        ],
      },
      {
        id: "behandeling",
        title: "Behandeling van tinnitus in de praktijk",
        blocks: [
          { type: "p", text: "De behandeling is altijd persoonlijk en afgestemd op uw situatie. Het doel is niet altijd om de tinnitus volledig te laten verdwijnen, maar vooral om de klachten te verminderen en beter hanteerbaar te maken." },
          { type: "h3", text: "Uitleg en advies" },
          { type: "p", text: "U krijgt inzicht in uw klachten en factoren die tinnitus be\u00efnvloeden, zoals stress, houding en spierspanning. Begrip helpt vaak al om de klachten beter te hanteren." },
          { type: "h3", text: "Oefentherapie" },
          { type: "p", text: "Gerichte oefeningen voor ontspanning van de kaakspieren, het verbeteren van de nekfunctie en houdingscorrectie." },
          { type: "h3", text: "Kaaktraining" },
          { type: "p", text: "Bij klachten zoals klemmen of knarsen leert u bewustwording van kaakspanning, ontspanningstechnieken en gezonde kaakgewoonten." },
          { type: "h3", text: "Manuele technieken" },
          { type: "p", text: "De therapeut kan spieren en gewrichten behandelen om spierspanning te verminderen, beweeglijkheid te verbeteren en pijn te verlichten." },
          { type: "h3", text: "Ademhaling en ontspanning" },
          { type: "p", text: "Stress speelt vaak een grote rol bij tinnitus. Daarom kan aandacht worden besteed aan ademhalingsoefeningen, ontspanningstechnieken en de balans tussen belasting en herstel. Veel pati\u00ebnten ervaren hierdoor meer rust en controle." },
        ],
      },
    ],
    faq: [
      { q: "Kan tinnitus overgaan?", a: "Soms neemt tinnitus vanzelf af, vooral als de oorzaak tijdelijk is. In andere gevallen blijft het aanwezig, maar kan de hinder sterk verminderen met de juiste begeleiding." },
      { q: "Is tinnitus gevaarlijk?", a: "Tinnitus is meestal niet gevaarlijk, maar kan wel vervelend zijn. Het is belangrijk om medische oorzaken uit te sluiten bij nieuwe klachten." },
      { q: "Helpt fysiotherapie echt bij tinnitus?", a: "Bij tinnitus die beïnvloed wordt door kaak-, nek- of spierspanning kan fysiotherapie zeker helpen om klachten te verminderen." },
      { q: "Waarom wordt tinnitus erger bij stress?", a: "Stress verhoogt spierspanning en de alertheid van het zenuwstelsel. Hierdoor kan het geluid sterker worden ervaren." },
      { q: "Moet ik leren leven met tinnitus?", a: "Voor veel mensen geldt dat de klachten beter hanteerbaar worden. Met de juiste aanpak is vaak meer mogelijk dan u denkt." },
    ],
    closing: {
      title: "Blijft u last houden van tinnitus?",
      paragraphs: [
        "Tinnitus kan een grote impact hebben op uw dagelijks leven. Gelukkig zijn er vaak mogelijkheden om de klachten te verminderen, zeker wanneer kaak, nek of spanning een rol spelen.",
        "Herkent u uw klachten in bovenstaande informatie? Neem gerust contact op voor advies of het maken van een afspraak. Samen kijken we wat we voor u kunnen betekenen.",
      ],
    },
  },
];
